### PR TITLE
fix: action mt so we can again concat actions from two different tables

### LINKED ISSUE #684: custom action example in README produces error
### Description
When I try to use the example config in the README for my_cool_custom_action, it produces an error. When I don't use the transform_mod function to wrap the custom function and just create the new action function directly, it works. 

It looks like the transform_mod way should add some nice stuff like conflict detection that the workaround would miss out on. Also, when I remove the transform_mod call, the workaround breaks with an error message from mt saying it expected a table.

**Expected Behavior**
Printing "This function ran after another action. Prompt_bufnr: <number>" when I hit <c-i> in normal mode from Telescope
**Actual Behavior**
E5108: Error executing lua ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:231: attempt to call local 'key_func' (a table value)

### Details

<details><summary> try to use the custom function in Telescope </summary>

1. nvim -nu test.vim
2. :Telescope <any>
3. .... bang here is the issue

<details><summary>Environment</summary>

- nvim --version output: 
NVIM v0.5.0-dev+1157-g0ab88c2ea
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-778

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
- Operating system: Arch Linux
- Telescope commit: I'm not really sure where to check this, but I just updated with packer and the current commit is 83e1993d875d88ab1b715bfdf36c10e6a8ed1ff4

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF
local transform_mod = require('telescope.actions.mt').transform_mod

local actions = require('telescope.actions')


-- or create your custom action

local my_cool_custom_action = transform_mod({ -- Doesn't work
  x = function()
   print("This function ran after another action. Prompt_bufnr: " .. prompt_bufnr)
    -- Enter your function logic here. You can take inspiration from lua/telescope/actions.lua
  end,
})
function actions.my_rad_custom_action(prompt_bufnr) -- workaround
   print("This function ran after another action. Prompt_bufnr: " .. prompt_bufnr)
end

-- Global remapping
------------------------------
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        -- To disable a keymap, put [map] = false
        -- So, to not map "<C-n>", just put
        ["<c-x>"] = actions.my_rad_custom_action,

        -- Otherwise, just set the mapping to the function that you want it to be.
        ["<C-i>"] = actions.select_horizontal,

        -- Add up multiple actions
        ["<CR>"] = actions.select_default + actions.center,

        -- You can perform as many actions in a row as you like
        ["<CR>"] = actions.select_default + actions.center + my_cool_custom_action,
      },
      n = {
        ["<esc>"] = actions.close,
        ["<C-i>"] = my_cool_custom_action,
      },
    },
  }
}

EOF
```

### PR DESCRIPTION
**Pull request by Conni2461**
Closes #684

- without actually changing the public interface
- without having a local table that keeps track of all actions

I could write more tests for this but its Friday evening and it was a long day ...

My take on https://github.com/nvim-telescope/telescope.nvim/pull/1093

### CODE REVIEW

**Comment by fdschmidt93** [comment]
While I much prefer that this avoids `registered_actions` in my `actions_mt`, this has other problems as elaborated upon in my PR:
- You `transform_mod` a custom action and then add or enhance custom action somewhere; it's not cleared since it doesn't have the identical actions metatable for which `actions._clear` is called at picker instantiation (test at bottom)
- Custom action cannot be mapped via strings ie `[<CR>] = "my_cool_action"` or `[<CR>] = actions.my_cool_action + action.select_vertical` since it's not part of actions (see `actions.register_actions`) -- allows (a) inspecting all actions more easily and (b) more unified interface when registering multiple actions at once
- You suggested  `smart`, `multi`, `entries` versions of actions should just work, which I wanted to do via parsing `__index` of actions that automatically registers the right version of the action (see [here](https://github.com/nvim-telescope/telescope.nvim/blob/979be4a446320c649287b6514e724db8facd4df9/lua/telescope/actions/init.lua#L46), which I wanted to wrap in `actions.register_actions`)

The above two things are much more gently solved by registering custom actions from `actions` (since we are just inserting into `redirect`) combined with your approach. OK if I incorporate this in my branch to synthesize advantages? Changing the interface I think has clear advantages and `actions.transform_mod` cannot be used right now anyways. Thank you for the exemplifying :)

------
Test the first point:
```lua
local action_mt = require "telescope.actions.mt"
local action_state = require "telescope.actions.state"
-- global for later inspection
custom_actions = action_mt.transform_mod({
  print_entry = function()
    print(vim.inspect(action_state.get_selected_entry()))
  end,
})
--

require 'telescope'.setup {
  defaults = {
    mappings = {
      i = {
        -- PR #1093
        ["<C-x>"] = custom_actions['print_entry'],
      },
    }
  }
}

-- later do something like thislocal actions = require "telescope.actions"
require("telescope.builtin").find_files {
  attach_mappings = function()
    custom_actions['print_entry']:enhance { post = actions.select_vertical }
    return true
  end,
}
-- inspect custom_actions
print(vim.inspect(custom_actions))
```

**Comment by Conni2461** [comment]
> elaborated upon in my PR

having read all of the conversation which probably was a mistake.

> You transform_mod a custom action and then add or enhance custom action somewhere; it's not cleared since it doesn't have the identical actions metatable for which actions._clear is called at picker instantiation (test at bottom)

i think i have a better way to solve this

> `[<CR>] = "my_cool_action"` or `[<CR>] = actions.my_cool_action + action.select_vertical`

if you have written an action i think you are able to map it via a table. the string part is only there for novice lua users who make the mistake that they forgot to require `actions`. i think this is nothing we need to support.

> Changing the interface I think has clear advantages

I still dont see the advantages and i prefer that `action_mt` is the lowers component in the stack. It allows us to easily test it in the spec file, especially if its stateless. Give me till Monday to address your concerns, in i think a better way. I do not want to block any of the other cool things :) but i already said it i have mixed feeling about your approach. I think it makes a lot more sense that the action object actually has a reference to the action function.

> Test the first point:

Btw for action_mt we talk spec file :laughing:

**Comment by Conni2461** [comment]
The thing i saying is we dont need additional tables, storing the actions. We already have this.

I found a bug and this isnt tested but i am out of time for now and need to go. Its done monday

**Comment by fdschmidt93** [comment]
> You suggested smart, multi, entries versions of actions should just work, which I wanted to do via parsing __index of actions that automatically registers the right version of the action (see [here](, which I wanted to wrap in actions.register_actions)

The only important thing I want to address is looking ahead to multi select actions. Could you please factor something in what I had in mind here if you agree with that? The other "advantages" would have been freebies in my suggestion. I dont wanna create new tables, just register into the right existing one. I hope it's clearer now, otherwise happy to discuss on Gitter.

**Comment by Conni2461** [comment]
> The only important thing I want to address is looking ahead to multi select actions.

I am confused by this because i dont see whats needed for you. Ive read now some of your multiselection implementation and i dont see how you keep it in mind. All i see is that you plan that register forbides registering actions with the names `smart` `multi` or `entries` in the name. 

> The other "advantages" would have been freebies in my suggestion

which other advantages? I am also clearing custom actions now and i dont think how this makes even remotely sense. You have a table of custom actions but you can also say `actions.my_custom` ? why is this in the telescope action module, thats just confusing. I know whats happening here in your code but from a outside perspective i never see a reason to do that. 

> I dont wanna create new tables

I am not criticizing that you create new tables (they are cheap) i am criticizing that this would make our lowest building block stateful. So first time registering a mod will be different from any other registering mod. It is not deterministic what happens on the second, third, fourth register, unless you unload the module and rerequire it. For example i register a table with the keys `a`, `b`, `c` then i register a table with the keys `c`, `d`, and `f` then i only have 5 functions in the store because the first `c` was overriden. I have a similar problem on a smaller scale in my implementation. If i have `a.x + b.x` then we end up with a new action `<user_tbl>.x` one function from table `b`.

> otherwise happy to discuss on Gitter

I prefer to have this conversation here public on github, so if tj or someone else who is interested can come in here and have 100% of the information needed :)

**Comment by fdschmidt93** [comment]
> All i see is that you plan that register forbides registering actions with the names smart multi or entries in the name.

The idea was to autogenerate these variants for any action, builtin or custom, on indexing. Registering is not in there yet but would have to be added. Of course that could be approached completely differently to begin with, eg all variants of an action are created upon creation/registering. Or we add them hardcoded.

> You have a table of custom actions but you can also say actions.my_custom

My idea was not to have a table of custom actions but unify all actions under `actions`. The freebies (which aren't necessary or anything) were "multi_custom_action" or `actions.custom_action". Again, can be viewed differently by separating builtin or custom actions. Ofc, what action can be multi etc also has to be considered.

> i am criticizing that this would make our lowest building block action_mt stateful.

Yes, understood and agree.

I've just clarified my original ideas and it doesn't really matter how we'll be doing that after all - what I wanted to propose is just one way of doing it I think is consistent.

I don't want to hold up anything here by discussing what we maybe should do, just go ahead :)

**Comment by Conni2461** [comment]
I think i am done with my proposal. @tjdevries needs to make the decision now what he wants.

I've not added `actions.register_action` we could do this but i personally prefer to keep the actions module as a set of actions that can be mapped. I mentioned that on multiple occasions but i am also not against it if there is a good reason for it.

So basically can now pick bits he wants from this pr and from #1093 and i am kinda done and move on now. If you want this and you register part, fdschmidt93, feel free to integrate this in your PR. I am not really attached to it, i only really care about that bit that i explained a couple of times now. This PR mainly tries to solve #684 nothing more, nothing less.

A shortcoming here right now is that we only clear actions that are mapped. Which means replace or enhance a action that was never mapped will not be cleared. We could just always clear `actions` + `actions.set` so it doesnt happen for builtin things.

File: lua/telescope/actions/mt.lua [hunk 1]
```diff
@@ -123,28 +140,35 @@ action_mt.create = function(mod)
   return mt
 end
 
-action_mt.transform = function(k, mt, mod, v)
+action_mt.transform = function(k, mt, v)
```
Comment (tjdevries) [inline lua/telescope/actions/mt.lua:143]: this is technically a breaking change, we could just use `_` for now if we wanted. Or just break it if we don't think anyone is really using it.

**Comment by tjdevries** [comment]
From reading both I think I prefer this method.

Are there any outstanding bugs w/ this implementation as it is now?

File: lua/telescope/actions/mt.lua [hunk 2]
```diff
@@ -45,18 +45,35 @@ action_mt.create = function(mod)
...
+      local new_action = setmetatable({}, action_mt.create())
       for _, v in ipairs(lhs) do
-        table.insert(new_actions, v)
+        table.insert(new_action, v)
+        new_action._func[v] = lhs._func[v]
+        new_action._static_pre[v] = lhs._static_pre[v]
+        new_action._pre[v] = lhs._pre[v]
+        new_action._replacements[v] = lhs._replacements[v]
+        new_action._static_post[v] = lhs._static_post[v]
+        new_action._post[v] = lhs._post[v]
```
Comment (tjdevries) [inline lua/telescope/actions/mt.lua:56]: can we write little helper function to copy these over? we do the same thing twice.

Also, have we documented what all the fields do? I don't remember if we did that or not. Could be helpful.

**Comment by fdschmidt93** [comment]
@Conni2461 bumping the PR, would you please finish this when you get the chance? :) I guess it integrates extensions better with custom actions, e.g. I'll work on the file browser extension and https://github.com/nvim-neorg/neorg-telescope soon.

**Comment by Conni2461** [comment]
I'll try to do it this weekend :) sorry for the slacking

File: lua/telescope/actions/mt.lua [hunk 3]
```diff
@@ -14,7 +14,7 @@ local run_replace_or_original = function(replacements, original_func, ...)
   return original_func(...)
 end
 
-action_mt.create = function(mod)
+action_mt.create = function()
```
[the remark this answers is not in the document]
Comment (Conni2461) [reply lua/telescope/actions/mt.lua:35]: Yeah we can keep track of the mts we created but i was never really a big fan of that idea.

Also I am not really sure how likely it is that we will run into this issue. That someone replaced a action and never mapped it (this is the only action that we currently don't clear).

I wanna sleep one night about that. Worst case is i add it with a `FIXME` and we deal with it sometime else :laughing: I dont wanna block fd so i will merge it this weekend. I will run it and see if there are any issues :laughing:

**Comment by Conni2461** [comment]
Will run today and merge this evening if there is no regression

**Comment by Conni2461** [comment]
Should work again and i didnt run into any regression, the whole day.

We will see what happens :laughing:
