### PR TITLE
fix: goto_file_selection performance issues, do not reload buffer if it is already loaded

### LINKED ISSUE #476: lsp_document_symbols are not working when buffer is not saved
### Description
lsp_document_symbols are not working when buffer is not saved, when I open lsp_document_symbols preview window is opening, but the when I want to jump to some symbol it doesn't work unless it is a saved buffer.
But when I save the file or buffer it works as expected

**Expected Behavior**
should jump to the symbol

**Actual Behavior**
E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:127: Vim(edit):E37: No write since last change (add ! to override)
Press ENTER or type command to continue

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope lsp_document_symbols
3. and here you'll get the error like this
4. E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:127: Vim(edit):E37: No write since last change (add ! to override)
Press ENTER or type command to continue
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
- Operating system: Mac OS
- Telescope commit: 9d4670c

</details>

<details><summary>Configuration</summary>
<p>

```viml
" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

" only i use this much from telescope plugin
```

### PR DESCRIPTION
**Pull request by oberblastmeister**
Fix #476 

Fixes:
- `goto_file_selection` general performance issues from `doautocmd` and unneeded api calls
- bug when entering the same buffer telescope will reload the enter buffer, making lsp restart and adding to the extreme slowness
- for example, when running `lsp.document_symbols` it will always enter the same buffer as was started in, just set the cursor to a different location. However, telescope reloads the entire buffer restarting lsp when it should just change to that location.

### CODE REVIEW

File: lua/telescope/pickers.lua [hunk 1]
```diff
@@ -327,6 +327,7 @@ function Picker:find()
   assert(self.finder, "Finder is required to do picking")
 
   self.original_win_id = a.nvim_get_current_win()
+  state.set_global_key('original_buf_id', a.nvim_get_current_buf())
```
Comment (Conni2461) [inline lua/telescope/pickers.lua:330]: We don't need a `state.set_global_key` just do that the api call when doing the get key access

File: lua/telescope/actions/init.lua [hunk 2]
```diff
@@ -73,71 +73,66 @@ function actions._goto_file_selection(prompt_bufnr, command)
...
-        if not ok then
-          log.debug("Failed to move to cursor:", err_msg, row, col)
-        end
+    if row and col then
+      local ok, err_msg = pcall(a.nvim_win_set_cursor, 0, {row, col})
+      if not ok then
+        log.debug("Failed to move to cursor:", err_msg, row, col)
       end
     end
-    vim.api.nvim_command("doautocmd filetypedetect BufRead " .. vim.fn.fnameescape(filename))
```
Comment (Conni2461) [inline lua/telescope/actions/init.lua:140]: Not having that breaks some things in the past. See here. I also said that this doesn't happen anymore so yeah. Maybe its fine to remove
https://github.com/nvim-telescope/telescope.nvim/issues/481#issuecomment-771453930

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (oberblastmeister) [reply lua/telescope/pickers.lua:330]: I am not sure what you mean

**Comment by Conni2461** [comment]
First of all thanks :) You need to rebase actions was completely rewritten in the last commit :)
I think the method is the same you just find the new one in actions/set.lua

Might also fix this https://github.com/nvim-telescope/telescope.nvim/issues/476 if you wanna test it. If not i gonna do it after this is rebased :)

File: lua/telescope/actions/init.lua (hunk 2 above)
Comment (oberblastmeister) [reply lua/telescope/actions/init.lua:140]: That doesn't seem to happen anymore. Also as I said above this pr will make it so that if the buffer is already loaded, it will not reload it again so the buffer local variables should not be reset. It will only load new buffers that haven't already been loaded.

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (Conni2461) [reply lua/telescope/pickers.lua:330]: Why do we need to to save it as state key? We just can get the current_buffer before doing edit. We are back there because the picker is already closed. Or am i wrong? He also already had that check in place it was just broken because of the normalize.

**Comment by oberblastmeister** [comment]
Yes I have tested and it fixes #476. Conceptually it also makes sense because that issue happens because previously we were using `edit`, which when used on the same file that you are currently in will error when the current file is not saved. Now if the file is the same as the current file it will not `edit`

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (oberblastmeister) [reply lua/telescope/pickers.lua:330]: That will not work because `get_current_buffer` before enter will get the telescope buffer, not the original one. Thats why we have to get the buffer *before* telescope has opened, hence setting a state key. Unless I am misunderstanding you

Comment (Conni2461) [reply lua/telescope/pickers.lua:330]: Telescope should be closed at this point in time. That works on current master. Printing the `bufnr` before edit gives me the correct one

Comment (oberblastmeister) [reply lua/telescope/pickers.lua:330]: You are right that telescope should be closed. My bad

**Comment by oberblastmeister** [comment]
Should be rebased now

File: lua/telescope/actions/set.lua [hunk 3]
```diff
@@ -50,71 +49,65 @@ set.edit = function(prompt_bufnr, command)
...
+  if entry_bufnr then
+    if command == 'edit' then
+      vim.cmd(string.format(":buffer %d", entry_bufnr))
+    elseif command == 'new' then
+      vim.cmd(string.format(":sbuffer %d", entry_bufnr))
+    elseif command == 'vnew' then
+      vim.cmd(string.format(":vert sbuffer %d", entry_bufnr))
+    elseif command == 'tabedit' then
+      vim.cmd(string.format(":tab sb %d", entry_bufnr))
+    end
```
Comment (tami5) [inline lua/telescope/actions/set.lua:95]: Here's c like switch which is way better then elseifs 

```lua
commands = {
  edit = string.format(":buffer %d", entry_bufnr),
  new = string.format(":sbuffer %d", entry_bufnr),
  vnew = string.format(":vert sbuffer %d", entry_bufnr),
  tabedit = string.format(":tab sb %d", entry_bufnr)
}
  vim.cmd(commands[command])

-- or better

vim.cmd(({
  edit = string.format(":buffer %d", entry_bufnr),
  new = string.format(":sbuffer %d", entry_bufnr),
  vnew = string.format(":vert sbuffer %d", entry_bufnr),
  tabedit = string.format(":tab sb %d", entry_bufnr)
})[command])


```

Comment (oberblastmeister) [reply lua/telescope/actions/set.lua:95]: I don't like creating a table just for an if/switch statement. It does look better but it creates 4 strings by default and also creates a table.

Comment (Conni2461) [reply lua/telescope/actions/set.lua:95]: The code lies in memory anyway so both ways have there drawback. You could only create that table once which would be in fact the best solution because it doesn't have to create the if else branches. But something like this would be optimal:
```lua
local tbl = {
  edit = 'buffer',
  new = 'sbuffer',
...
}
string.format("%s %d", tbl[command], entry_bufnr)
```

But this is code that runs only when with `builtin.buffers` and `:buffer` etc is basically free. So i wouldn't touch that. But thats up to you guys.

File: lua/telescope/actions/init.lua (hunk 2 above)
Comment (Conni2461) [reply lua/telescope/actions/init.lua]: I will test this now. But i think its also no longer necessary.

File: lua/telescope/actions/set.lua [hunk 4]
```diff
@@ -50,71 +49,65 @@ set.edit = function(prompt_bufnr, command)
...
+    -- to put stuff into `filename`
+    local value = entry.value
+    if not value then
+      print("Could not do anything with blank line...")
+      return
     end
 
-    local preview_win = state.get_status(prompt_bufnr).preview_win
-    if preview_win then
-      a.nvim_win_set_config(preview_win, {style = ''})
```
Comment (Conni2461) [inline lua/telescope/actions/set.lua:83]: I think we had this because sometimes preview options were applied to the main window. I am not sure if this would happen again if we remove that part.

File: lua/telescope/actions/set.lua [hunk 5]
```diff
@@ -50,71 +49,65 @@ set.edit = function(prompt_bufnr, command)
...
+      vim.cmd(string.format(":buffer %d", entry_bufnr))
+    elseif command == 'new' then
+      vim.cmd(string.format(":sbuffer %d", entry_bufnr))
+    elseif command == 'vnew' then
+      vim.cmd(string.format(":vert sbuffer %d", entry_bufnr))
+    elseif command == 'tabedit' then
+      vim.cmd(string.format(":tab sb %d", entry_bufnr))
+    end
+  else
+    filename = path.normalize(vim.fn.fnameescape(filename), vim.fn.getcwd())
```
Comment (Conni2461) [inline lua/telescope/actions/set.lua:97]: We kinda wanna want speed now so we should use `vim.loop.cwd` :D no more viml :rofl:

File: lua/telescope/actions/set.lua (hunk 3 above)
Comment (oberblastmeister) [reply lua/telescope/actions/set.lua:95]: thanks for the clarification

Comment (oberblastmeister) [reply lua/telescope/actions/set.lua]: using your solution now

**Comment by Conni2461** [comment]
I hate that i am still nitpicking :laughing: I wouldn't put any action stuff in `utils.lua` currently. Just do a local table in front of that that function. With a clear name :) Thanks i am testing in 5-10min.
Looks really good to me thanks :)

File: lua/telescope/actions/set.lua [hunk 6]
```diff
@@ -40,6 +39,24 @@ set.select = function(prompt_bufnr, type)
   return set.edit(prompt_bufnr, action_state.select_key_to_edit_key(type))
 end
 
+local edit_buffer
+do
```
Comment (Conni2461) [inline lua/telescope/actions/set.lua:43]: Testing now but another tip :)
```lua
local edit_buffer = (function()
  local map = {}

  return function(command, bufnr)
    ...
  end
end)()
```

Runs first time (and only once) and initializes `edit_buffer`.

Comment (oberblastmeister) [reply lua/telescope/actions/set.lua:43]: Thats cool. I think this is the purpose of `do .. end` though and in my opinion `do .. end` is clearer. I think this is small so I hope you are okay with me just leaving it :smile:

Comment (Conni2461) [reply lua/telescope/actions/set.lua:43]: Do end just opens a block. Its a little bit different but i won't argue about some syntax sugar :laughing: Both works fine

**Comment by Conni2461** [comment]
`vim.api.nvim_command("doautocmd filetypedetect BufRead " .. vim.fn.fnameescape(filename))` is still needed. I can't get my folds to work without it. And i know @mhartington will not like it being removed :rofl:. Me too btw

**Comment by oberblastmeister** [comment]
Could you explain how the folds do not work? I have tested and they work for me. `vim.api.nvim_command("doautocmd filetypedetect BufRead " .. vim.fn.fnameescape(filename))` is *very* slow and the user would expect that a file that is already loaded should open up immediately.

**Comment by Conni2461** [comment]
Its fast without it because we just not execute filetype autocommands. There is probably some neovim bug (or missing some vim patches) that makes them not run. I think i remember tj sending me a PR that tried to fix that.

Example what i have in my config (and probably @mhartington) as well:
```lua
local configs = parsers.get_parser_configs()
local ft_str = table.concat(vim.tbl_map(function(ft) return configs[ft].filetype or ft end, parsers.available_parsers()), ',')
vim.cmd('autocmd Filetype ' .. ft_str .. ' setlocal foldmethod=expr foldexpr=nvim_treesitter#foldexpr()')

-- or you can just do something like this for testing
vim.cmd('autocmd Filetype lua :lua print("hello from ft autocmd")')
```

For me it only prints with `doautocmd`

**Comment by oberblastmeister** [comment]
@Conni2461 I have to go right now. I will come back and test in about an hour.

**Comment by mhartington** [comment]
_You rang...._

**Comment by Conni2461** [comment]
ober wants to remove `vim.api.nvim_command("doautocmd filetypedetect BufRead " .. vim.fn.fnameescape(filename))` but that breaks folds or all ft autocommands. Just for you information. I am still arguing :laughing:

**Comment by mhartington** [comment]
😄 ah alright.

I guess the better question is why would removing this break folds? 
Is this something that needs to be fixed in neovim?

**Comment by Conni2461** [comment]
Yeah i think that PR https://github.com/neovim/neovim/pull/13247 (tj send that one to me some time ago) tries to fix that. I just build that branch. Doesn't help.

**Comment by oberblastmeister** [comment]
This is getting really wierd. I think that this is a neovim issue. My `Filetype` autocommands are not even working in the first place so that needs to be fixed before I test the other thing. Editing a file regular without `telescope.nvim` will not even trigger filetype autocommands. I made an [issue](https://github.com/neovim/neovim/issues/14000#issue-814857729) on neovim.

File: lua/telescope/actions/set.lua (hunk 3 above)
Comment (tami5) [reply lua/telescope/actions/set.lua]: You are welcome, :D

File: lua/telescope/actions/set.lua [hunk 7]
```diff
@@ -40,6 +39,24 @@ set.select = function(prompt_bufnr, type)
...
+  }
+
+  edit_buffer = function(command, bufnr)
+    command = map[command]
+    if command == nil then
+      error('There was no associated buffer command')
+    end
+    vim.cmd(string.format("%s %d", command, bufnr))
+  end
+end
```
Comment (tami5) [inline lua/telescope/actions/set.lua:58]: a version without if else :laughing:, ignore it if you don't like it its okay. I'm just sharing my thoughts

```lua
local errmsg = "There was no associated buffer command"

edit_buffer = function(command, bufnr)
  return map[command] and vim.cmd(map[command]  .. " " .. bufnr) or error(errmsg) 
end

```

**Comment by oberblastmeister** [comment]
@Conni2461 I tested and for me the folds don't even work with the `vim.api.nvim_command("doautocmd filetypedetect BufRead " .. vim.fn.fnameescape(filename))` so the autocommand seems useless and just makes entering a file very slow. For me whenever I open a file with telescope folds don't work, but when I open a file with `edit` it works. The weird thing is that when folds are not working when I do `set foldexpr?` it shows `nvim_treesitter#foldexpr()` but somehow it is not recognizing that. I think that this is some neovim or treesitter buf and that an `doautocmd` seems like it is unnecessary to retrigger everything and make it slow.

**Comment by Conni2461** [comment]
Yeah we ran into that as well. So removing the action.center makes it work. It just soooooo weird. I have that locally in my config. mappings.lua just does `select_default + center` on default. Really weird :laughing:

But you might be right it would be better to remove it. We could add a new action. So i can locally do `select_default + do_auto` or i just add a do auto locally

**Comment by oberblastmeister** [comment]
@Conni2461 changing the actions to only do `select_default` does not fix my folds. I think we should merge this pr because the `doautocmd` does not seem to be doing anything and this pr also fixes #476. For the treesitter folds not working we should move to #559

**Review by Conni2461 — APPROVED** [review]
Yeah i agree. I used rust and rust_analyzer yesterday and with `doautocmd` it starts lsp twice. Which isn't bad for clangd and others i usually use but rust_analyzer, which is usually really great has a bad startup time.

Sorry @mhartington you gotta do `:e` for now. I will search more why it just doesn't work because doing `setlocal foldmethod` or `setlocal foldexpr` shows the correct values. You can also create a new action which basically just does `vim.cmd'e'` and do:
`default_select + custom_action` in your config.

Check readme for more info :)

Code LGTM btw :rofl:
