### PR TITLE
fix: use nil for the default diagnostics severity

### LINKED ISSUE #2661: `Telescope diagnostics` always returns `"no diagnostics found"` even when diagnostics exist
### Description

`Telescope diagnostics` always returns `"no diagnostics found"` even when diagnostics exist.

### Neovim version

```markdown
NVIM v0.10.0-dev-881+g7a3fef9e3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora Linux 38 (Workstation Edition)

### Telescope version / branch / rev

main

### checkhealth telescope

```markdown
==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `emoji` ~
- No healthcheck provided

Telescope Extension: `file_browser` ~
- No healthcheck provided

Telescope Extension: `frecency` ~
- OK sqlite.lua installed.
- OK nvim-web-devicons installed.

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `harpoon` ~
- No healthcheck provided

Telescope Extension: `hop` ~
- No healthcheck provided

Telescope Extension: `media_files` ~
- No healthcheck provided

Telescope Extension: `neoclip` ~
- No healthcheck provided

Telescope Extension: `noice` ~
- No healthcheck provided

Telescope Extension: `notify` ~
- No healthcheck provided

Telescope Extension: `persisted` ~
- No healthcheck provided

Telescope Extension: `refactoring` ~
- No healthcheck provided

Telescope Extension: `smart_history` ~
- No healthcheck provided
```

### Steps to reproduce

1. Open a simple `lua` file with `nvim -nu minimal.lua example.lua`
2. Start the lua lsp with  `LspStart`
3. Use `LspInfo` to confirm the `lua lsp` is attached to buffer
4. Create a syntax error in the file
5. Show diagnostics with `Telescope diagnostics` command

### Expected behavior

`Telescope diagnostics` should show a window with all diagnostic issues.

### Actual behavior

`Telescope diagnostics` always returns `"no diagnostics found"` even when diagnostics exist.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      "neovim/nvim-lspconfig",
      "williamboman/mason.nvim",
      "williamboman/mason-lspconfig.nvim",
      {
        "nvim-telescope/telescope.nvim",
        requires = {
          "nvim-lua/plenary.nvim",
          { "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
_G.load_config = function()
  require("telescope").setup()
  require("telescope").load_extension("fzf")
  require("mason").setup()
  require("mason-lspconfig").setup {
    ensure_installed = { "lua_ls" },
  }
  require("lspconfig").lua_ls.setup {}
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system({
    "git",
    "clone",
    "--depth=1",
    "https://github.com/wbthomason/packer.nvim",
    install_path,
  })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

### PR DESCRIPTION
**Pull request by delphinus**
# Description

https://github.com/neovim/neovim/pull/24736 has introduced a new syntax for severity format in `vim.diagnostic.get()`.

Fix #2661

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

- [x] `:Telescope diagnostics` at a file with diagnostic warnings.

**Configuration**:
* Neovim version (nvim --version):
   - Neovim HEAD
      ```
      NVIM v0.10.0-dev-3455+g18062f70d-Homebrew
      Build type: Release
      LuaJIT 2.1.0-beta3
      ```
* Operating system and version: macOS Ventura 13.4.1

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

File: lua/telescope/builtin/__diagnostics.lua [hunk 1]
```diff
@@ -69,7 +69,7 @@ local diagnostics_to_tbl = function(opts)
   opts.severity_limit = convert_diagnostic_type(severities, opts.severity_limit)
   opts.severity_bound = convert_diagnostic_type(severities, opts.severity_bound)
 
-  local diagnosis_opts = { severity = {}, namespace = opts.namespace }
+  local diagnosis_opts = { severity = nil, namespace = opts.namespace }
```
Comment (Conni2461) [inline lua/telescope/builtin/__diagnostics.lua:72]: we can't just do that. for 2 reasons, 
- we only wanna do that for nvim 0.10-dev and later 
- `diagnosis_opts.severity["min"] = opts.severity_limit` in line 84 will explode if we initialize severity to nil,

so i wouldnt touch this line, i'd rather think we should do this after we initialized `diagnosis_opts` with everything (i think line 90). so basically check if `#severity == 0` and nvim version > 0.9 set severity back to `nil`

**Review by Conni2461 — CHANGES_REQUESTED** [review]

File: lua/telescope/builtin/__diagnostics.lua (hunk 1 above)
Comment (delphinus) [reply lua/telescope/builtin/__diagnostics.lua]: Thank for review. I add a check Neovim > 0.9.1. 89fb6ee

Comment (jamestrew) [reply lua/telescope/builtin/__diagnostics.lua]: probably unlikely this matters but maybe just `vim.version().minor > 9` in case neovim core releases a 0.9.2 without the api changes to `vim.diagnostic.get()`?

Comment (delphinus) [reply lua/telescope/builtin/__diagnostics.lua]: @jamestrew sorry for late.

Yes, it is enough that we can check it by the version > 0.9.x. Fixed in 9dc3d90

**Review by jamestrew — APPROVED** [review]
