### PR TITLE
fix(builtin.tags): custom filename width (#1820)

### LINKED ISSUE #1820: How to change tags picker's file path width?
### Description

I can not find the way by docs

### Neovim version

```markdown
0.6.1
```

### Operating system and version

macos 12.0.1

### checkhealth telescope

```markdown
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  -- Packer can manage itself
	use 'wbthomason/packer.nvim'
  	use 'neovim/nvim-lspconfig' -- Collection of configurations for the built-in LSP client
	use 'kyazdani42/nvim-web-devicons'
	use 'overcache/NeoSolarized'
	use {'neoclide/coc.nvim', branch = 'release'}
	use 'gfanto/fzf-lsp.nvim'
	use 'nvim-treesitter/nvim-treesitter'
	use {
  		'nvim-lualine/lualine.nvim',
  		requires = { 'kyazdani42/nvim-web-devicons', opt = true }
	}
	use {
    	'kyazdani42/nvim-tree.lua',
   	 	requires = {
      		'kyazdani42/nvim-web-devicons', -- optional, for file icon
    	},
    	config = function() require'nvim-tree'.setup {} end
	}
	use 'bagrat/vim-buffet'
	use 'voldikss/vim-floaterm'
	use 'nvim-lua/plenary.nvim'
	use 'hoschi/yode-nvim'
	use {
  		'nvim-telescope/telescope.nvim',
  		requires = { {'nvim-lua/plenary.nvim'}
	},
	use {
		'nvim-telescope/telescope-fzf-native.nvim',
		run = 'make' 
	}
}
end)
```

### Steps to reproduce

:Telescope tags

### Expected behavior

_No response_

### Actual behavior

图片

### Minimal config

```Lua
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  -- Packer can manage itself
	use 'wbthomason/packer.nvim'
  	use 'neovim/nvim-lspconfig' -- Collection of configurations for the built-in LSP client
	use 'kyazdani42/nvim-web-devicons'
	use 'overcache/NeoSolarized'
	use {'neoclide/coc.nvim', branch = 'release'}
	use 'gfanto/fzf-lsp.nvim'
	use 'nvim-treesitter/nvim-treesitter'
	use {
  		'nvim-lualine/lualine.nvim',
  		requires = { 'kyazdani42/nvim-web-devicons', opt = true }
	}
	use {
    	'kyazdani42/nvim-tree.lua',
   	 	requires = {
      		'kyazdani42/nvim-web-devicons', -- optional, for file icon
    	},
    	config = function() require'nvim-tree'.setup {} end
	}
	use 'bagrat/vim-buffet'
	use 'voldikss/vim-floaterm'
	use 'nvim-lua/plenary.nvim'
	use 'hoschi/yode-nvim'
	use {
  		'nvim-telescope/telescope.nvim',
  		requires = { {'nvim-lua/plenary.nvim'}
	},
	use {
		'nvim-telescope/telescope-fzf-native.nvim',
		run = 'make' 
	}
}
end)
```

### PR DESCRIPTION
**Pull request by codemicmaves**
fix #1820

### CODE REVIEW

File: lua/telescope/make_entry.lua [hunk 1]
```diff
@@ -918,11 +918,11 @@ function make_entry.gen_from_ctags(opts)
   }
   local hidden = utils.is_path_hidden(opts)
   if not hidden then
-    table.insert(display_items, 1, { width = 30 })
+    table.insert(display_items, 1, { width = opts.fname_width or 30 })
   end
 
   if opts.show_line then
-    table.insert(display_items, 1, { width = 30 })
+    table.insert(display_items, 1, { width = opts.fname_width or 30 })
```
Comment (Conni2461) [inline lua/telescope/make_entry.lua:925]: Not here. (or make another opts) because this is not about the contents of the line not the filename

File: doc/telescope.txt [hunk 2]
```diff
@@ -872,6 +872,8 @@ builtin.tags({opts})                                          *builtin.tags()*
                                     true)
         {only_sort_tags} (boolean)  if true we will only sort tags (default:
                                     false)
+        {fname_width}    (number)   Defines the width of the filenames section
+                                    (default: 30)
```
Comment (Conni2461) [inline doc/telescope.txt:876]: documentation is autogenerated needs to be added here https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/init.lua#L102-L117

und both `builtin.tags` and `builtin.current_buffer_tags`

**Comment by codemicmaves** [comment]
I have addressed both comments in the latest issue.

File: lua/telescope/make_entry.lua [hunk 3]
```diff
@@ -925,6 +925,10 @@ function make_entry.gen_from_ctags(opts)
     table.insert(display_items, 1, { width = 30 })
   end
 
+  if opts.fname_width then
+    table.insert(display_items, 1, { width = opts.fname_width })
+  end
```
Comment (Conni2461) [inline lua/telescope/make_entry.lua:930]: Did you test this? I think this ^ will not work. I only meant you dont want `opts.fname_width or 30` in line 925 because that is the setting for the show_line option. Change in line 921 was good. (even tho i prefer `vim.F.if_nil` over `or` here

Comment (codemicmaves) [reply lua/telescope/make_entry.lua:930]: Okay, both changes seemed to work initially. So, I did another bout of thorough testing. I think there is a slightly bigger issue here. Since width is prepended to the display items, different widths do not work for all combinations of options. So far the path and show_line work well only because the widths are the same by default (30).  I'll try to figure out how to set the correct width for the correct component.

To explain the issue better: {show_line = false, fname_width = 10} does the expected thing of making file paths to 10 wide. But, {show_line = true, fname_width = 10} makes the "Line" component to be 10 wide instead of file path because it gets pushed down in the display_items table.

Comment (Conni2461) [reply lua/telescope/make_entry.lua:930]: Thats why i said this change above isnt good and we were looking for your initial change

```lua
  if not hidden then
    table.insert(display_items, 1, { width = vim.F.if_nil(opts.fname_width, 30) })
  end
```

**Comment by codemicmaves** [comment]
I have made the necessary changes. But, I think there is a different bug here due to the following lines:
` lua
    if hidden then
      return displayer {
        entry.tag,  -- 1.a
        scode,  -- 1.b
      }
    else
      return displayer {
        filename, -- 2.a
        entry.tag, -- 2.b
        scode, -- 2.c
      }
    end
`
Based on the value of hidden above either 2 or 3 items are stacked into the view. However, we only add widths to at most 2 items earlier. So the width always gets assigned to the bottom two entries. So if we had the following parameters `{ path_display='shorten', fname_width=10, show_line=true }` then `fname_width` will be used for `entry.tag` at 2.b.

I can raise a separate issue and fix this separately if that makes things cleaner.

**Comment by Conni2461** [comment]
I finished it. 

Thanks for the PR. :) Pro tip for the future make a new branch before making change and dont use master ;)
