### PR TITLE
fix: add opts.bufnr and opts.winnr to builtin picker

### LINKED ISSUE #1678: Cannot run any LSP picker from builtin picker
### Description

Open Telescope builtin picker by run `:Telescope` without any command selected
Select `lsp_document_symbol` from builtin picker
Telescope log the error `LSP: no client attached`
I assume Telescope `check_capabilities` getting attached client from buffer `0`. In this case, I suspect buffer 0 is Telescope builtin itself so no client is attached

image

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux tuanvuong 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1/ Open builtin picker by `:Telescope`
2/ Select `lsp_document_symbol`
3/ View log

### Expected behavior

Able to bring up LSP picker

### Actual behavior

log `LSP: no client attached` shown

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by jamestrew**
When buffer/window specific pickers are selected from the `:Telescope builtin` picker, the current buffer & window becomes Telescope itself making many of the pickers practically useless.

This PR sets `opts.bufnr` and `opts.winnr` when `:Telescope builtin` is ran. Buffer and window sensitive pickers can then reference those values when called via the `builtin` picker (if not set, use the current bufnr/winnr via `vim.api.nvim_get_current_buf/win()`).

closes #1678

Considering the builtin picker is probably where many new users try out the various builtin pickers, I think getting all the pickers functional from within the builtin picker is quite important.

Fixes or tweaks to allow for fix:
 - `files.treesitter`
 - `files.current_buffer_fuzzy_find`
 - `files.current_buffer_tags`
 - `git.bcommits`
 - `lsp.references`
 - `lsp.definitions`
 - `lsp.type_definitions`
 - `lsp.implementations`
 - `lsp.document_symbols`
 - `lsp.code_actions`
 - `lsp.range_code_actions`
 - `lsp.workspace_symbols`
 - `lsp.dynamic_workspace_symbols`
 - `diagnostics.get`

I think I got them all.

TODO: 
- [x] `current_buffer_ctags` still needs work in its `make_entry`
 - [x] double check and test all changes
 - [x] clean up

### CODE REVIEW

File: lua/telescope/builtin/files.lua [hunk 1]
```diff
@@ -271,16 +271,14 @@ files.treesitter = function(opts)
...
     print "No parser for the current buffer"
     return
   end
 
   local ts_locals = require "nvim-treesitter.locals"
-  local bufnr = opts.bufnr or vim.api.nvim_get_current_buf()
-
   local results = {}
-  for _, definitions in ipairs(ts_locals.get_definitions(bufnr)) do
+  for _, definitions in ipairs(ts_locals.get_definitions(opts.bufnr)) do
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:281]: so prior to this `bufnr` was never nil now it can be if you just do `Telescope treesitter` or with `:lua ....`

Not sure if we want this. I am pretty sure we should do `opts.bufnr = vim.F.if_nil(opts.bufnr, vim.api.nvim_get_current_buf())`

File: lua/telescope/builtin/files.lua [hunk 2]
```diff
@@ -307,17 +305,16 @@ end
 
 files.current_buffer_fuzzy_find = function(opts)
   -- All actions are on the current buffer
-  local bufnr = vim.api.nvim_get_current_buf()
-  local filename = vim.fn.expand(vim.api.nvim_buf_get_name(bufnr))
-  local filetype = vim.api.nvim_buf_get_option(bufnr, "filetype")
+  local filename = vim.fn.expand(vim.api.nvim_buf_get_name(opts.bufnr))
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:308]: same

File: lua/telescope/builtin/git.lua [hunk 3]
```diff
@@ -101,8 +101,10 @@ local get_current_buf_line = function(winnr)
 end
 
 git.bcommits = function(opts)
-  opts.current_line = (opts.current_file == nil) and get_current_buf_line(0) or nil
-  opts.current_file = vim.F.if_nil(opts.current_file, vim.fn.expand "%:p")
+  -- local winnr = opts.winnr or vim.api.nvim_get_current_win()
+  -- local bufnr = opts.bufnr or vim.api.nvim_get_current_buf()
+  opts.current_line = (opts.current_file == nil) and get_current_buf_line(opts.winnr) or nil
+  opts.current_file = vim.F.if_nil(opts.current_file, vim.api.nvim_buf_get_name(opts.bufnr))
```
Comment (Conni2461) [inline lua/telescope/builtin/git.lua:107]: same but for winnr and bufnr

File: lua/telescope/builtin/init.lua [hunk 4]
```diff
@@ -446,6 +446,8 @@ local apply_config = function(mod)
   for k, v in pairs(mod) do
     mod[k] = function(opts)
       opts = opts or {}
+      opts.bufnr = opts.bufnr or vim.api.nvim_get_current_buf()
+      opts.winnr = opts.winnr or vim.api.nvim_get_current_win()
```
Comment (Conni2461) [inline lua/telescope/builtin/init.lua:450]: oh you do it here. That works.

File: lua/telescope/builtin/git.lua [hunk 5]
```diff
@@ -101,8 +101,10 @@ local get_current_buf_line = function(winnr)
 end
 
 git.bcommits = function(opts)
-  opts.current_line = (opts.current_file == nil) and get_current_buf_line(0) or nil
-  opts.current_file = vim.F.if_nil(opts.current_file, vim.fn.expand "%:p")
+  -- local winnr = opts.winnr or vim.api.nvim_get_current_win()
+  -- local bufnr = opts.bufnr or vim.api.nvim_get_current_buf()
```
Comment (Conni2461) [inline lua/telescope/builtin/git.lua:105]: please delete these comments

File: lua/telescope/builtin/lsp.lua [hunk 6]
```diff
@@ -13,21 +13,18 @@ local utils = require "telescope.utils"
...
       return
     end
 
     local locations = {}
     if result then
-      vim.list_extend(
-        locations,
-        vim.lsp.util.locations_to_items(result, vim.lsp.get_client_by_id(ctx.client_id).offset_encoding) or {}
-      )
+      vim.list_extend(locations, vim.lsp.util.locations_to_items(result) or {})
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:27]: no we need `vim.lsp.get_client_by_id(ctx.client_id).offset_encoding` as second param to `locations_to_items` because of changes in nightly

File: lua/telescope/builtin/lsp.lua [hunk 7]
```diff
@@ -75,7 +72,7 @@ local function list_or_jump(action, title, opts)
       elseif opts.jump_type == "vsplit" then
         vim.cmd "vnew"
       end
-      vim.lsp.util.jump_to_location(flattened_results[1], vim.lsp.get_client_by_id(ctx.client_id).offset_encoding)
+      vim.lsp.util.jump_to_location(flattened_results[1])
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:75]: same

File: lua/telescope/builtin/lsp.lua [hunk 8]
```diff
@@ -145,18 +142,14 @@ lsp.document_symbols = function(opts)
 end
 
 lsp.code_actions = function(opts)
-  local params = vim.F.if_nil(opts.params, vim.lsp.util.make_range_params())
+  local params = vim.F.if_nil(opts.params, vim.lsp.util.make_range_params(opts.winnr))
+  local lnum = vim.api.nvim_win_get_cursor(opts.winnr)[1]
 
   params.context = {
-    diagnostics = vim.lsp.diagnostic.get_line_diagnostics(),
+    diagnostics = vim.lsp.diagnostic.get_line_diagnostics(opts.bufnr, lnum - 1),
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:149]: ?

we should move to `vim.diagnostic.get` here

File: lua/telescope/builtin/lsp.lua [hunk 9]
```diff
@@ -145,18 +142,14 @@ lsp.document_symbols = function(opts)
...
   }
 
-  local results_lsp, err = vim.lsp.buf_request_sync(
-    0,
-    "textDocument/codeAction",
-    params,
-    vim.F.if_nil(opts.timeout, 10000)
-  )
+  local results_lsp, err = vim.lsp.buf_request_sync(opts.bufnr, "textDocument/codeAction", params, opts.timeout)
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:152]: ? ... what happend to `vim.F.if_nil(opts.timeout, 10000)`

File: lua/telescope/builtin/lsp.lua [hunk 10]
```diff
@@ -269,10 +262,10 @@ lsp.code_actions = function(opts)
     end
 
   local execute_action = opts.execute_action
-    or function(action, offset_encoding)
+    or function(action, _)
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:265]: offset is needed

File: lua/telescope/builtin/lsp.lua [hunk 11]
```diff
@@ -448,9 +438,10 @@ local function apply_checks(mod)
   for k, v in pairs(mod) do
     mod[k] = function(opts)
       opts = opts or {}
+      opts.timeout = vim.F.if_nil(opts.timeout, 10000)
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:441]: we have like one timeout in this file. No need for this

**Review by Conni2461 — CHANGES_REQUESTED** [review]
Dont like the unrelated changes

**Comment by jamestrew** [comment]
Thanks for the thorough review.
I've reflected the requested changes.

File: lua/telescope/builtin/init.lua [hunk 12]
```diff
@@ -382,7 +378,6 @@ builtin.lsp_code_actions = require_on_exported_call("telescope.builtin.lsp").cod
 
 --- Lists any LSP actions for a given range, that can be triggered with `<cr>`
 ---@param opts table: options to pass to the picker
----@field timeout number: timeout for the sync call (default: 10000)
```
Comment (Conni2461) [inline lua/telescope/builtin/init.lua:385]: Good call removing all this invalid docs. Thanks but `timeout` is still valid for `lsp_range_code_actions` because of same underlying function

File: lua/telescope/builtin/lsp.lua (hunk 8 above)
Comment (Conni2461) [reply lua/telescope/builtin/lsp.lua:152]: image

I dont know whats happening here. Can we use `vim.diagnostic.get`?

I think this should do the trick
```
vim.diagnostic.get(opts.bufnr, { lnum = lnum - 1})
```

File: lua/telescope/builtin/lsp.lua [hunk 13]
```diff
@@ -272,7 +273,7 @@ lsp.code_actions = function(opts)
     or function(action, offset_encoding)
       if action.edit or type(action.command) == "table" then
         if action.edit then
-          vim.lsp.util.apply_workspace_edit(action.edit, offset_encoding)
+          vim.lsp.util.apply_workspace_edit(action.edit)
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:276]: offset_encoding needs to stay because of nightly

**Comment by Conni2461** [comment]
Looks way better now. Thanks :)

Left a couple more remarks. Can you also rebase because of this: https://github.com/nvim-telescope/telescope.nvim/commit/2553236fe185a5b0ce61ebc587aee9f65d2d747b

File: lua/telescope/builtin/lsp.lua [hunk 14]
```diff
@@ -77,7 +77,7 @@ local function list_or_jump(action, title, opts)
       elseif opts.jump_type == "vsplit" then
         vim.cmd "vnew"
       end
-      vim.lsp.util.jump_to_location(flattened_results[1], offset_encoding)
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:80]: this is just `offset_encoding`. Its defined in line 68

**Comment by Conni2461** [comment]
@galbacarys dont see how this is related. Please open an issue

**Review by Conni2461 — APPROVED** [review]
LGTM thanks :)
