### PR TITLE
fix(preview): update buffer previewer to upstream changes

### LINKED ISSUE #2149: current_buffer_fuzzy_find preview with treesitter highlighting broken on Neovim 0.8
### Description

```
Error executing Lua callback: ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:413: attempt to call method '_get_hl_from_capture' (a nil value)
stack traceback:
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:413: in function 'v'
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:514: in function <...cker/start/telescope.nvim/lua/t
elescope/builtin/init.lua:483>
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:109: in function <...te/pack/packer/start/telescope.
nvim/plugin/telescope.lua:108>
```

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-v2NLjd/neovim-0.8.0~ubuntu1+git2022
08262348-b0e052a8b-c99271b19=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_
SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -
Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
double-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallt
hrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLA
RATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/buil
d/neovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/build/cmake.config -I/build
/neovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/src -I/build/neovim-v2NLjd/n
eovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/.deps/usr/include -I/usr/include -I/build/ne
ovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/build/src/nvim/auto -I/build/ne
ovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/build/include
Compiled by buildd@lcy02-amd64-030
```

### Operating system and version

wsl2 ubuntu

### Telescope version / branch / rev

 tag⋅=⋅"0.1.0"

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `env`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

:Telescope  current_buffer_fuzzy_find

### Expected behavior

_No response_

### Actual behavior

:Telescope  current_buffer_fuzzy_find   
image
image

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by clason**
https://github.com/neovim/neovim/pull/19931 removed `_get_hl_from_capture(id)` since captures are now implicitly mapped to highlight groups with the same name.

Fixes #2149

(PSA: "Neovim master" always means "latest HEAD" -- this will intentionally break on older nightlies.)

### CODE REVIEW

File: lua/telescope/builtin/__files.lua [hunk 1]
```diff
@@ -410,7 +410,14 @@ files.current_buffer_fuzzy_find = function(opts)
       end,
     })
     for id, node in query:iter_captures(root, opts.bufnr, 0, -1) do
-      local hl = highlighter_query:_get_hl_from_capture(id)
+      local hl
+      -- update to changes on Neovim master, see https://github.com/neovim/neovim/pull/19931
+      -- TODO(clason): remove when dropping support for Neovim 0.7
+      if vim.fn.has "nvim-0.8" == 1 then
```
Comment (Conni2461) [inline lua/telescope/builtin/__files.lua:416]: we could store that eval in an local outside of the for loop so we dont check that every time.

Comment (clason) [reply lua/telescope/builtin/__files.lua:416]: True -- although then I'd probably make it global so it can be used in other compat checks?

Comment (clason) [reply lua/telescope/builtin/__files.lua:416]: And/or refactor this into a local `get_hl_from_capture_id` function?

**Comment by Conni2461** [comment]
Thanks :) Tested it, seems to work. Just a small nit, that might be worth fixing, after that we can merge.

> (PSA: "Neovim master" always means "latest HEAD" -- this will intentionally break on older nightlies.)

We say: "Neovim (v0.7.0) or the latest neovim nightly commit is required for telescope.nvim to work." so i am fine with that

(Maybe that should say 0.7.2 or 0.7.*, haven't updated our readme since the last release :laughing:)

**Comment by clason** [comment]
As long as we're agreed that we only support the latest release and the latest commit on master :)

By the way, there's a `has('nvim-0.7')` check at the top of this file -- isn't that redundant with the one in `init.lua`?

**Review by Conni2461 — APPROVED** [review]

**Comment by Conni2461** [comment]
> By the way, there's a has('nvim-0.7') check at the top of this file -- isn't that redundant with the one in plugin/telescope.lua?

Yeah i also noticed this, but for some recent never removed it :grimacing: 

Thanks again :)
