### PR TITLE
fix: previewers & entry maker file encoding

### LINKED ISSUE #2415: Live grep can't show non utf-8 content correctly
### Description

When the content showed by Telescope has accented characters like in the word `acentuação` and the content is in `latin1` the characters is not displayed correctly.

### Neovim version

```markdown
NVIM v0.9.0-dev-869+g964ae205a-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora 37

### Telescope version / branch / rev

v0.1.1

### checkhealth telescope

```markdown
1 ──────────────────────────────────────────────────────────────────────────────
  2 telescope: require("telescope.health").check()
  3
  4 Checking for required plugins
  5 - OK plenary installed.
  6 - OK nvim-treesitter installed.
  7
  8 Checking external dependencies
  9 - OK rg: found ripgrep 13.0.0
 10 - OK fd: found fd 8.2.1
 11
 12 ===== Installed extensions =====
 13
```

### Steps to reproduce

1. Open a file with some accented characters with latin1 encoding.
2. Run `:Telescope live_grep`
3. Search for a term in this file
4. Preview can't show accented characters correctly

### Expected behavior

Preview should be displayed correctly as it is with uft-8 files:

image

### Actual behavior

Preview is displayed incorrecly.

image

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by jamestrew**
# Description

Previewers and some entry_makers currently has poor support for non UTF8 encoded files.
This PR looks to add a new option `file_encoding` to pickers with for previewers `file_previewer` & `grep_previewer`, `qflist_previewer`.
This new option is consumed by `buffer_previewer.file_maker` to do some string processing with `vim.iconv`. A similar thing also happens in `make_entry.gen_from_vimgrep`.

Fixes #2415 
## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

This change impacts the following pickers:
`live_grep`
`grep_string`
`find_files`
`git_files`
`treesitter`
`current_buffer_fuzzy_find`
`oldfiles`
`buffers`
`marks`
`lsp_dynamic_workspace_symbols`
`lsp_workspace_symbols`
`lsp_document_symbols`
`lsp_implementations`
`lsp_type_definitions`
`lsp_definitions`
`lsp_outgoing_calls`
`lsp_incoming_calls`
`lsp_references`

- [x] For each picker above, confirm previewer and entries look good for non-UTF8 encoded files

1.  create file with `acentuação`
2.  write file with latin1 encoding `:write ++enc=latin1`
3.  test pickers with `:Telescope <picker> file_encoding=latin1` and verify previewer/entry

- [x] Regression test with standard utf8 file and no `file_encoding` option

**Configuration**:
* Neovim version (nvim --version): `NVIM v0.9.0-dev-1070+g2630341db` 
* Operating system and version: `Linux archlinux 6.2.5-arch1-1`

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

File: lua/telescope/previewers/buffer_previewer.lua [hunk 1]
```diff
@@ -59,8 +59,10 @@ end
 local function split(s, sep, plain, opts)
   opts = opts or {}
   local t = {}
+  local line
```
[the remark this answers is not in the document]
Comment (jamestrew) [reply lua/telescope/previewers/buffer_previewer.lua:62]: I was probably trying to be cute and do some premature (and possibly incorrect) performance optimization.

**Comment by jamestrew** [comment]
> Maybe we should default back to using the input text if we get `nil` back from the `iconv` just in case? I'm not super familiar with file encoding stuff though.

I'm not super familiar either but probably a good idea to handle this case. Updated the code.

File: lua/telescope/previewers/buffer_previewer.lua [hunk 2]
```diff
@@ -60,7 +60,12 @@ local function split(s, sep, plain, opts)
   opts = opts or {}
   local t = {}
   for c in vim.gsplit(s, sep, plain) do
-    table.insert(t, c)
+    local line = opts.file_encoding and vim.iconv(c, opts.file_encoding, "utf8") or c
+    if line ~= nil then
```
Comment (tjdevries) [inline lua/telescope/previewers/buffer_previewer.lua:64]: i prefer something like `line = line or c` and then do the insert.

**Comment by tjdevries** [comment]
sorry, one little nit and then we can merge. Thanks :)

File: lua/telescope/previewers/buffer_previewer.lua (hunk 2 above)
Comment (jamestrew) [reply lua/telescope/previewers/buffer_previewer.lua:64]: Actually, going back to the handling `nil` thing, if `vim.iconv` returns `nil` wouldn't the above "ternary operator" handle it and just return `c`.
We should be able to simply `table.insert(t, line)`.

**Comment by Conni2461** [comment]
thanks :)

**Comment by Conni2461** [comment]
and sorry for my really late response. i just rebased and fixed the conflicts

**Comment by brneor** [comment]
Just tested this change. Even though I can now see the preview correctly I still can't search for this characters.

Fox example, in a file with the content `acentuação`, using `Telescope live_grep file_encoding=latin1` a search for `ç` gives me no results.

**Comment by jamestrew** [comment]
I can take a look at this. I think we simply need to pass the `file_encoding=latin1` option to ripgrep.
