### PR TITLE
fix(help_tags): show help tags on windows (#3126)

### LINKED ISSUE #3126: BUG: help_tags does not show any help tags on Windows
### Description

help_tags does not show any help tags on Windows

### Neovim version

```markdown
0.10.0
```

### Operating system and version

Windows 10

### Telescope version / branch / rev

a71ef5a

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0 (rev e50df40a19)
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. `:Telescope help_tags`
2. Nothing is shown

### Expected behavior

The picker should show help tags

### Actual behavior

Empty selection in help_tags

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by xudyang1**
On Windows, `builtin.help_tags` picker does not show any help tags.

To fix this, the following changes are needed:

1. `util.path_tail` checks unix separator `/` on Windows and leave the original implementation intact on unix systems.

2. Line endings should be taken carefully on Windows. `vim.split` with only newline `\n` character as separator may result in unexpected crash when parsing large files. When splits on lines are needed, call it with `\r?\n`, or even set up a wrapper function in utils is more prefered.

Fixes #3126

# Description

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context

Fixes #3126 (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

- [x] `util.path_tail` on Windows, Linux, and MacOS
- [x] `util.split_lines` on Windows, Linux and MacOS

**Configuration**:
* Neovim version (nvim --version): 0.10.0
* Operating system and version: Windows 10 22H2

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

File: lua/telescope/utils.lua [hunk 1]
```diff
@@ -216,13 +216,25 @@ end)()
 utils.path_tail = (function()
   local os_sep = utils.get_separator()
 
-  return function(path)
-    for i = #path, 1, -1 do
-      if path:sub(i, i) == os_sep then
-        return path:sub(i + 1, -1)
+  if os_sep == "/" then
```
Comment (xudyang1) [inline lua/telescope/utils.lua:219]: `vim.fn.fnamemodify(path, ":p:t")` may replace `util.path_tail(path)`, but the former may be slower and has dependency on neovim

File: lua/tests/automated/utils_spec.lua [hunk 2]
```diff
@@ -307,3 +307,92 @@ describe("transform_path", function()
...
+    if not file then
+      return nil
+    end
+    local content = file:read "*a"
+    file:close()
+    return content
+  end
+
+  local newline = [[./lua/tests/fixtures/split_lines/newline.txt]]
+  local carriage_newline = [[./lua/tests/fixtures/split_lines/carriage_newline.txt]]
```
Comment (jamestrew) [inline lua/tests/automated/utils_spec.lua:369]: is it strictly necessary to use real files for these?
I think I would prefer just using lua strings if possible

**Review by jamestrew — COMMENTED** [review]
Thanks, I'll try to take a closer look in the coming days.

File: lua/tests/automated/utils_spec.lua (hunk 2 above)
Comment (xudyang1) [reply lua/tests/automated/utils_spec.lua]: That is definitely better! Unnecessary testing fixtures were removed.

File: lua/telescope/utils.lua [hunk 3]
```diff
@@ -213,16 +213,30 @@ utils.path_smart = (function()
   end
 end)()
 
+-- vim.fn.fnamemodify(path, ":p:t") may replace util.path_tail(path),
+-- but the former may be slower and has dependency on neovim
```
Comment (jamestrew) [inline lua/telescope/utils.lua:217]: nit: this "dependency on neovim" comment isn't really necessary.
This whole plugin is basically entirely dependent on neovim.

also out of curiosity, I benchmarked `fnamemodify` vs `path_tail` against ~80k files.
```
hyperfine 'nvim -l fnamemodify.lua' 'nvim -l path_tail.lua' --warmup 10 --runs 10
Benchmark 1: nvim -l fnamemodify.lua
  Time (mean ± σ):     238.0 ms ±   4.3 ms    [User: 119.9 ms, System: 108.0 ms]
  Range (min … max):   232.3 ms … 243.1 ms    10 runs

Benchmark 2: nvim -l path_tail.lua
  Time (mean ± σ):      28.8 ms ±   3.0 ms    [User: 21.9 ms, System: 6.3 ms]
  Range (min … max):    25.5 ms …  34.8 ms    10 runs

Summary
  nvim -l path_tail.lua ran
    8.27 ± 0.88 times faster than nvim -l fnamemodify.lua
```
kinda surprised by this result.

**Review by jamestrew — COMMENTED** [review]
Couple of minor things but otherwise looks good to me. Gave all the touched pickers/previewers a try and they work for me (at least on linux).

File: lua/telescope/init.lua [hunk 4]
```diff
@@ -164,7 +165,7 @@ telescope.__format_setup_keys = function()
     table.insert(result, "")
     table.insert(result, string.format("%s*telescope.defaults.%s*", string.rep(" ", 70 - 20 - #name), name))
     table.insert(result, string.format("%s: ~", name))
-    for _, line in ipairs(vim.split(desc, "\n")) do
+    for _, line in ipairs(utils.split_lines(desc)) do
```
[the remark this answers is not in the document]
Comment (xudyang1) [reply lua/telescope/init.lua]: Code is reverted. `init.lua` now does not load `telescope.utils`.

File: lua/telescope/utils.lua (hunk 3 above)
Comment (xudyang1) [reply lua/telescope/utils.lua]: I thought it would be only 2 to 3 times faster. `vim.fn` calls `viml` calls c code, probably that's why it's much slower than pure lua codes.

**Comment by jamestrew** [comment]
Thanks a lot!
