### PR TITLE
start: Working w/ async jobs

### LINKED ISSUE #750: initial_mode=normal doesn't populate selections
### Description

`initial_mode=normal` doesn't populate the selections until you go into insert mode

**Expected Behavior**

`initial_mode=normal` should populate buffers exactly like `initial_mode=insert`, but in normal mode.

**Actual Behavior**

`initial_mode=normal` doesn't populate the selections until you go into insert mode

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim test.vim
2. :Telescope buffers initial_mode=normal
3. selections are empty
4. `i` to change to insert mode
5. selections are populated

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+370469b
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210405-60261-zzx58z/build/config -I/tmp/neovim-20210405-60261-zzx58z/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210405-60261-zzx58z/build/src/nvim/auto -I/tmp/neovim-20210405-60261-zzx58z/build/include
Compiled by joe@Josephs-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-370469b_2/share/nvim"

Run :checkhealth or more info
```
- Operating system: macos big sur 11.2.2 (20D80) (M1 macbook air)
- Telescope commit: `5bd6f5c`

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

### LINKED ISSUE #777: regression when using no `prompt_prefix`
Probably related #709. But have not testing it

`:Telescope find_files prompt_prefix=` doesn't show any files until you start typing.

Annoyingly pinging my old boss @tjdevries

### LINKED ISSUE #1018: using initial_mode = "normal" search results are not displaying property (small bug)
### Description

Using "initial_mode" option with builtin.buffers function causes telescope to
not refresh and therefore leaving empty "results" display

**Expected Behavior**

Expected "results" display when using "initial_mode" option in builtin.buffers
function exactly when new telescope search buffer lists window spawns, my
reason is because my buffer list is usually rather short, so id rather use hjkl
keys to navigate without pressing escape

**Actual Behavior**

*you're lol.
When telescope search buffer list spawns the results are empty, but when i go
to insert mode (press i) results of buffer list appear

### Details

<details><summary>Reproduce</summary>
i use "<leader>fb" keybind to call ":Telescope buffers" 
and have a initial_mode = "normal", option in buffers section 
(I'm not sure how to describe it programmatically sorry)
(don't worry I'll link my short telescope.rc.vim below)

</details>

<details><summary>Environment</summary>
I'm note sure what to write there...

- nvim --version output: 
- NVIM v0.5.0

- Operating system: 
- Arch linux
no. Arch GNU/linux lol

- Telescope commit: 
1. https://pastebin.com/eUrDF6GR ~/.config/nvim/after/plugin/telescope.rc.vim
2. :Telescope live_grep
3. https://i.imgur.com/tcaKrQD.png 
(it just hangs like that, but refreshes when in insert mode)
4.  https://i.imgur.com/lQbfgot.png

</details>

<details><summary>https://pastebin.com/eUrDF6GR</summary>
<p>

```viml
https://pastebin.com/eUrDF6GR
```

### PR DESCRIPTION
**Pull request by tjdevries**
This should just work by checking this only. No backwards incompat changes (hopefully)

----

old text

Fixes #750
Fixes #777 
Fixes #1018 

Latest Clip: https://clips.twitch.tv/SincereQuaintNostrilWholeWheat-9VR2k_is7r1F01VN <-- LiveGrep from home directory

Example of some cool improvements :) https://clips.twitch.tv/GrossRenownedOryxKappaClaus-mTa6exkBdFuym-F5

Will keep on working on this cause I'm (obviously) quite excited :laughing:

### CODE REVIEW

**Comment by rockerBOO** [comment]
https://clips.twitch.tv/FairCrowdedQuailTooSpicy-LwegLYuYF0aA8l5B 

Try out this PR. Needs plenary PR updated as well.

**Comment by lynndylanhurley** [comment]
@tjdevries the input lag when typing is 1000% better. this is amazing improvement!

I am still seeing some lag when navigating through the selections before the results have finished processing. The issue is intermittent tho so I can't reliably reproduce

**Comment by JimmyCozza** [comment]
This is incredible.

I tested this in the v8 codebase, which I think is pretty large.
Here's a side-by-side of `live_grep` using the master branches of `telescope` and `plenary` vs the async_v2 branches.

## Master Branches 
### (I typed in all of "sparse_array" right away, it just blocks at the first character)

https://user-images.githubusercontent.com/8379106/126004629-b19daa6e-8778-4062-a159-ce795f27d723.mp4




## Async_v2 Branches
### :fire: 

https://user-images.githubusercontent.com/8379106/126004527-57e640d3-ea11-4876-8ba2-070fcf0cd995.mp4

**Comment by ecosse3** [comment]
That is sick! I really appreciate your hard work ❤️ Will it work with `telescope-fzf-native.nvim` or it doesn't need it anymore?

**Comment by oberblastmeister** [comment]
Yes it will still work

**Comment by nklmilojevic** [comment]
This is a huge improvement, awesome work!

**Comment by tjdevries** [comment]
Cool :) I will work on fixing some UI & other related items. I just wanted to confirm that this would work for other people and wasn't some crazy glitch on my machine :)

Thanks!

**Comment by n3wborn** [comment]
Huge fan of Telescope here. Once again, so many thanks for your work !

**Comment by kristijanhusak** [comment]
I gave this a test. It is much faster, but input is swallowing some letters randomly, and results are not always as expected (not on this video, but on my private project). Here's the video of letters issue:

https://user-images.githubusercontent.com/1782860/126036728-f2a19c1d-f860-4a87-886e-0b80065fe6d8.mp4

**Comment by numToStr** [comment]
I am getting a `coroutine failed` error whenever I attempt to delete the last letter of the search entry. Once the error pops up the `live_grep` doesn't respond to any further inputs. FWIW this issue doesn't seem to appear when I delete the word with `<C-w>`.

https://user-images.githubusercontent.com/24727447/126040890-2dd9bf81-b067-49af-9fc7-3f7c86b7b98c.mp4

**Comment by kblcuk** [comment]
Nice! 💪 

The cursor movement now seems to behave rather interestingly, when you're scrolling up and then long-running search completes / gets updated results.

**Comment by nashio** [comment]
Just tried this in my whole directory of projects:
after typing one word:
before: 17sec
after: 2sec

I did notice one issue, in the async_2 branches, when typing in the search box, the characters sometimes get swallowed. For ex. Typing "pokemon" sometimes I get "p kem n"

**Comment by tjdevries** [comment]
My last commit messed up some prompt things -- plz ignore anything with the prompt for now. For now I've gotten enough feedback to confirm a few things and track down some others.

Thanks everyone! I'll post again when I have new stuff to test

**Comment by JSchrtke** [comment]
I just tried this on windows as well, it's ripping fast, very nice.

I did find a bug, though I'm not sure if that is related to the prompt thing you said you messed up. Anyway, to reproduce:

* `:Telescope live_grep`
* Type one char
* Backspace
* `Error executing lua callback: ...js\.vim\plugged\plenary.nvim\lua\plenary\async\async.lua:14: The coroutine failed with this message: ...js\.vim\plugged\telescope.nvim\lua\telescope\pickers.lua:389: bad argument #1 to 'last' (table expected, got nil)`

**Comment by medwatt** [comment]
I ran `Telescope find_files` on my home directory, which has some 200,000 files. It was much faster than before. I then closed `Telescope` with `ESC` and opened it again with `Telescope find_files` on the same directory. This time, I was not able to close it with `ESC` and I had to kill the neovim process for it to stop.

**Comment by metalelf0** [comment]
Ok, I've been trying this feature, and here's my feedback.

The UI is not blocking anymore. This is obviously a good point.

However, in my use case, the "real results" still take a long time to display. My scenario is a Rails app, with a total file number (in the git repo, so including assets etc.) of ~ 2300 files, and the repository size (as in `git count-objects -vH` is ~50MB.

Let's say, I open the `live-grep` window, and I start typing in the `UserProfile` string; I immediately see some results, while typing, that are obviously incorrect - I still haven't finished typing the string - but when I finish typing, it takes like 3-4 seconds to display the final results. 

If I instead just paste `UserProfile` in the search box, results are shown immediately, so I guess it's because the plugin is still elaborating all the searches (`U`, `Us`, `Use`, `User`, `UserP` etc.) before getting to displaying the results.

My suggestion would be to add a (configurable?) delay parameter before actually performing the search - e.g., 200 or 300ms. I guess this would dramatically improve the user experience.

Thanks a lot for the amazing work!

**Comment by oberblastmeister** [comment]
we could add a configurable sleep call here in addition to the schedule https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/pickers.lua#L370. It was actually here before but was removed. Another thing we need to do is cancellation on yield

**Comment by lynndylanhurley** [comment]
Cancellation on yield would be amazing

**Comment by oberblastmeister** [comment]
there is a pr here https://github.com/nvim-lua/plenary.nvim/pull/171

**Comment by tjdevries** [comment]
@metalelf0 can you paste your config or send a link to it so I can see exactly what you're running? I'm having a hard time reproducing that.

**Comment by metalelf0** [comment]
@tjdevries  my config is @ https://github.com/metalelf0/dot-files/tree/master/.config/nvim , I'm sorry but it's ugly! I need to show it a little more love :/

**Comment by tjdevries** [comment]
Hmm, I'm not sure.

I just added an option for `debounce` in pickers, so you can do:

```lua
require('builtin').live_grep { debounce = 100 }
```
to add a 100 ms debounce. You can check it out if it makes things better for you

**Comment by metalelf0** [comment]
> Hmm, I'm not sure.
> 
> I just added an option for `debounce` in pickers, so you can do:
> 
> ```lua
> require('builtin').live_grep { debounce = 100 }
> ```
> 
> to add a 100 ms debounce. You can check it out if it makes things better for you

Yes, it's much better now. Thanks!

**Comment by dottorblaster** [comment]
Just landed on this after setting up neovim and grepping the interwebs about `live_grep` quirks. I just wanted to personally thank you for this PR and the outstanding work!

File: lua/telescope/builtin/lsp.lua [hunk 1]
```diff
@@ -1,16 +1,15 @@
-local actions = require "telescope.actions"
+local conf = require("telescope.config").values
+local channel = require("plenary.async.control").channel
+
 local action_state = require "telescope.actions.state"
+local actions = require "telescope.actions"
+local conf = require("telescope.config").values
```
Comment (Conni2461) [inline lua/telescope/builtin/lsp.lua:6]: duplicated `local conf = require`

File: lua/telescope/finders.lua [hunk 2]
```diff
@@ -68,6 +66,7 @@ function JobFinder:_find(prompt, process_result, process_complete)
   end
 
   local on_output = function(_, line, _)
+    print("LINE:", line)
```
Comment (Conni2461) [inline lua/telescope/finders.lua:69]: should be removed

File: lua/telescope/finders/async_job_finder.lua [hunk 3]
```diff
@@ -18,58 +15,62 @@ return function(opts)
 
     local command = table.remove(command_list, 1)
 
-    return {
+    local res = {
       command = command,
       args = command_list,
     }
+
+    TelescopeLastGrep = res
```
Comment (Conni2461) [inline lua/telescope/finders/async_job_finder.lua:23]: I think this is a leftover

File: lua/telescope/path.lua [hunk 4]
```diff
@@ -48,6 +48,10 @@ path.shorten = (function()
 end)()
 
 path.normalize = function(filepath, cwd)
+  if true then
```
Comment (Conni2461) [inline lua/telescope/path.lua:51]: We no longer use this module

Its deprecated You can remove it

File: lua/telescope/sorters.lua [hunk 5]
```diff
@@ -462,6 +462,9 @@ sorters.get_fzy_sorter = function(opts)
   }
 end
 
+-- TODO: Could probably do something nice where we check their conf
+--          and choose their default for this.
+--          But I think `fzy` is good default for now.
```
Comment (Conni2461) [inline lua/telescope/sorters.lua:467]: I send you a diff for that in discord some time ago if you still wanna do it :laughing:

File: lua/telescope/pickers.lua [hunk 6]
```diff
@@ -346,101 +342,108 @@ function Picker:find()
...
   self.__on_lines = tx.send
 
-  local main_loop = async(function()
+  local find_id = self:_next_find_id()
+
+  local main_loop = async.void(function()
+    self.sorter:_init()
+
+    -- Do filetype last, so that users can register at the last second.
+    pcall(a.nvim_buf_set_option, prompt_bufnr, "filetype", "TelescopePrompt")
```
Comment (Conni2461) [inline lua/telescope/pickers.lua:368]: You miss a new filetype

https://github.com/nvim-telescope/telescope.nvim/blob/273942cc478b356d7b2e0a5211281daaef69d161/lua/telescope/pickers.lua#L483-L485

because some people had issue in result window with FastFold or so i can't remember

**Comment by tjdevries** [comment]
todo:
- make `writer` work for jobs
- make sure `do_selection` is good

File: lua/telescope/pickers.lua [hunk 7]
```diff
@@ -1056,60 +1033,62 @@ end
...
-    state.set_global_key("current_line", current_line)
-
-    status_updater()
-
-    self:clear_extra_rows(results_bufnr)
-    self:highlight_displayed_rows(results_bufnr, prompt)
-    if self.sorter then
-      self.sorter:_finish(prompt)
+  elseif selection_strategy == "closest" then
+    if prompt == "" and self.default_selection_index ~= nil then
```
Comment (Conni2461) [inline lua/telescope/pickers.lua:1083]: prompt doesn't exist in this function. `self:_get_prompt()`

**Comment by Conni2461** [comment]
For everyone testing this and getting a error with `finders.new_table` picker like `git_commits`, and way more. I think this is the fix that needs to be added to plenary before merging this PR.

```diff
diff --git a/lua/plenary/async/control.lua b/lua/plenary/async/control.lua
index 16f963e..257ba71 100644
--- a/lua/plenary/async/control.lua
+++ b/lua/plenary/async/control.lua
@@ -209,7 +209,7 @@ M.channel.mpsc = function()
     end
     local val = deque:popright()
     deque:clear()
-    return unpack(val)
+    return unpack(val or {})
   end
 
   return Sender, Receiver
```

We should try not to forget that :laughing:

File: lua/telescope/pickers.lua [hunk 8]
```diff
@@ -997,10 +971,11 @@ function Picker:get_status_updater(prompt_win, prompt_bufnr)
       return
     end
 
-    local prompt_len = #current_prompt
+    local text = self:get_status_text(opts)
+    local prompt_len = #self.prompt_prefix + #current_prompt
 
-    local padding = string.rep(" ", vim.api.nvim_win_get_width(prompt_win) - prompt_len - #text - 3)
-    vim.api.nvim_buf_clear_namespace(prompt_bufnr, ns_telescope_prompt, 0, 1)
+    local padding = string.rep(" ", vim.api.nvim_win_get_width(prompt_win) - prompt_len - #text)
```
Comment (Conni2461) [inline lua/telescope/pickers.lua:977]: Dont remember why we had a `- 3` here but right now the max count is "out of screen"

File: lua/telescope/entry_manager.lua [hunk 9]
```diff
@@ -155,7 +155,10 @@ function EntryManager:add_entry(picker, score, entry)
     info.looped = info.looped + 1
 
     if container[2] > score then
-      -- print("Inserting: ", picker, index, node, new_container)
+      return self:_insert_container_before(picker, index, node, new_container)
+    end
+
+    if score < 1 and container[2] == score and #entry.ordinal < #container[1].ordinal then
```
Comment (fdschmidt93) [inline lua/telescope/entry_manager.lua:161]: Would be wrapping `#entry.ordinal < #container[1].ordinal` in a `break_ties(current_entry, existing_entry)` function that users can override and pass via `opts` to `pickers:new()` something we want? Which defaults to preferring shorter ordinals, of course.

Would address
#1080 (I guess that's what OP wanted)
#939 (I think)

and I'm sure allows for cool customization of other stuff down the line.

Comment (tjdevries) [reply lua/telescope/entry_manager.lua:161]: Yeah, let's do that in a follow up PR
