### PR TITLE
fix: preview = true

### LINKED ISSUE #2101: highlighter error when `preview` is a boolean
### Description

`:h telescope.setup()` says:

```
        To disable previewing, set it to false. If you have disabled previewers                                                                                                                          
        globally, but want to opt in to previewing for single pickers, you will have to                                                                                                                  
        pass preview = true or preview = {...} (your config) to the opts of                                                                                                                              
        your picker.  
```

but then with an invocation like `live_grep({ preview = true })`, telescope complains:

```
Error executing vim.schedule lua callback: ...lugged/telescope.nvim/lua/telescope/previewers/utils.lua:83: attempt to index field 'preview' (a boolean value)                                            
stack traceback:                                                                                                                                                                                         
        ...lugged/telescope.nvim/lua/telescope/previewers/utils.lua:83: in function 'highlighter'                                                                                                        
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:242: in function ''                                                                                                                  
        vim/_editor.lua: in function <vim/_editor.lua:0> 
```
from the referenced line at https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/previewers/utils.lua#L82, it seems like extra handling is needed for the boolean case - something like return early if `opts.preview` is `false`, else create the object if `opts.preview` is true?

```
opts.preview = opts.preview or {}
```

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 12

### Telescope version / branch / rev

0.1.0

### checkhealth telescope

```markdown
N/A
```

### Steps to reproduce

`lua require('telescope.builtin').live_grep({ preview = true })`

### Expected behavior

_No response_

### Actual behavior

error is raised

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by Conni2461**
fix #2101

### CODE REVIEW

File: lua/telescope/previewers/buffer_previewer.lua [hunk 1]
```diff
@@ -152,11 +152,13 @@ local scroll_fn = function(self, direction)
 end
 
 previewers.file_maker = function(filepath, bufnr, opts)
-  opts = opts or {}
-  opts.preview = opts.preview or {}
+  opts = vim.F.if_nil(opts, {})
+  -- TODO(conni2461): here shouldn't be any hardcoded magic numbers ...
+  opts.preview = vim.F.if_nil(opts.preview, {})
```
Comment (cfal) [inline lua/telescope/previewers/buffer_previewer.lua:157]: wouldn't this still set `opts.preview` to `true` or `false` when it's non nil, and then the following dictionary lookups would still fail?

Comment (Conni2461) [reply lua/telescope/previewers/buffer_previewer.lua:157]: no because the data is already changed at this point in time, we do that on previewer instanzing 

https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/previewers/buffer_previewer.lua#L38-L46

Do you still experience #2101 with this PR?
