### PR TITLE
fix: error from unset LspDiagnosticSign & introduce opts.no_sign

### LINKED ISSUE #603: Error on LSP workspace diagnostics when unsetting LSP sign
### Description

Using lsp_workspace_diagnostics give error when unsetting LSP sign
**Expected Behavior**

It works fine
**Actual Behavior**

Error like : 
image

### Details

<details><summary>Reproduce</summary>

1. Start nvim and LSP on a project
2. :lua vim.fn.sign_define("LspDiagnosticsSignError", {text = "", numhl = "LspDiagnosticsDefaultError"})
3. :Telescope lsp_workspace_diagnostics
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1117-g6995fad26
- Operating system: Linux
- Telescope commit: 908752fc67f0aff43e35ffb175b5e6226874bad5

</details>

<details><summary>Configuration</summary>
<p>

```lua
local vim = vim
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()

  use {'neovim/nvim-lspconfig'}
  use {
    'nvim-telescope/telescope.nvim',
    requires = {'nvim-lua/popup.nvim','nvim-lua/plenary.nvim'}
  }
end)

require('telescope').setup{}
require('lspconfig').rust_analyzer.setup {}

```

### PR DESCRIPTION
**Pull request by fdschmidt93**
This should fix #603  as per discussion in the issue, specifically

- The signs if empty default to {E, W, I, H}
- `opts.no_sign` can be used to turn off the sign entirely
- Additionally: line header width is automatically set and now also respects 1'000s of lines adequately

### CODE REVIEW

**Comment by Conni2461** [comment]
Still happens. Because `vim.fn.sign_getdefined` will still return nil and a table access `[1]` will throw that error. 

Steps to reproduce.
- Start nvim
- Open File
- Wait for lsp
- Telescope lsp_document_symbols everything works
- `call sign_undefine("LspDiagnosticsSignWarning")`
- Telescope lsp_document_symbols error

File: lua/telescope/make_entry.lua [hunk 1]
```diff
@@ -858,16 +858,24 @@ function make_entry.gen_from_lsp_diagnostics(opts)
...
 
-  local signs = {}
-  for _, v in pairs(lsp_type_diagnostic) do
-    signs[v] = vim.trim(vim.fn.sign_getdefined("LspDiagnosticsSign" .. v)[1].text)
+  local signs
+  if not opts.no_sign then
+    signs = {}
+    for _, v in pairs(lsp_type_diagnostic) do
+      local status, sign = pcall(
+        function() return vim.trim(vim.fn.sign_getdefined("LspDiagnosticsSign" .. v)[1].text) end)
```
Comment (Conni2461) [inline lua/telescope/make_entry.lua:866]: Wasn't an argument for `pcall` you can do this for example.
```lua
local get_table = function()
  return nil
  -- return { 'a' }
end

print((get_table() or {})[1])
```

Tell me what you like more, after that i can either merge or you update

Comment (Conni2461) [reply lua/telescope/make_entry.lua:866]: The thing is we basically just need a table so `x or {}` should just work

Comment (fdschmidt93) [reply lua/telescope/make_entry.lua:866]: I'll have to admit `pcall` is more simple here as otherwise there are two issues to fix:
1. The original issue empties out the text of the highlighting group with "" resulting in `SignTable[1].text` being nil - that was what I originally fixed
2. Your issue unbinds the diagnostic making`SignTable` nil, which is just as valid (maybe more) though probably less common than original issue

I'd quickly recommit though with comment as to why pcall is required. Sounds good?

Comment (Conni2461) [reply lua/telescope/make_entry.lua:866]: Sounds good

**Review by Conni2461 — APPROVED** [review]
LGTM

Thanks :)
