### PR TITLE
fix: allow find_command along with options

### LINKED ISSUE #1635: setup.pickers options do not work
### Description

This does not set the `hidden` option
```lua
require('telescope').setup{
  pickers = {
    find_files = {
      find_command = { "fd", "--type", "f", "--strip-cwd-prefix" },
      hidden = true,
    },
  },
}
```
This works
```lua
require('telescope').setup{
  pickers = {
    find_files = {
      find_command = { "fd", "--type", "f", "--strip-cwd-prefix", "--hidden" },
    },
  },
}
```
But the docs says that there's a `hidden` option we can set

https://github.com/nvim-telescope/telescope.nvim/blob/9d0034df79506af0ee0f102f1f5c6eec59e20e90/doc/telescope.txt#L745-L767

`:lua require"telescope.builtin".find_files()`

### Neovim version

```markdown
NVIM v0.7.0-dev+761-g0d7a97224
```

### Operating system and version

Arch linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `git_worktree`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

.

### Expected behavior

I expect with the `hidden` option shows the hidden files if true

### Actual behavior

The `hidden` option does not work.
The `find_command` option works

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by pedro757**
fix #1635

### CODE REVIEW

File: lua/telescope/builtin/files.lua [hunk 1]
```diff
@@ -145,106 +145,126 @@ files.grep_string = function(opts)
...
 end
 
--- TODO: Maybe just change this to `find`.
--- TODO: Support `find` and maybe let people do other stuff with it as well.
-files.find_files = function(opts)
+local function which_find_command(opts)
+  local command = opts.find_command
+  if command then
+    return command[1]
+  end
```
Comment (pedro757) [inline lua/telescope/builtin/files.lua:152]: Is this a good idea?

Are there cases when the first element of the table is not the command?

Comment (Conni2461) [reply lua/telescope/builtin/files.lua:152]: What if someone implemented his own find implementation and uses this as `find_command`. Then we will return nil.

Comment (Conni2461) [reply lua/telescope/builtin/files.lua:152]: Then its not handled by the `find_command_options` if ?

File: lua/telescope/builtin/files.lua [hunk 2]
```diff
@@ -145,106 +145,126 @@ files.grep_string = function(opts)
...
   local find_command = opts.find_command
   local hidden = opts.hidden
   local no_ignore = opts.no_ignore
   local follow = opts.follow
   local search_dirs = opts.search_dirs
 
-  if search_dirs then
-    for k, v in pairs(search_dirs) do
-      search_dirs[k] = vim.fn.expand(v)
+  if command == "fd" then
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:174]: Cant we refactor this now ? if `command == "fd" or command == "fd_find" or command == 'rg'` all do the same if i am not wrong

File: lua/telescope/builtin/files.lua [hunk 3]
```diff
@@ -145,106 +145,126 @@ files.grep_string = function(opts)
...
+    end
+    if search_dirs ~= nil then
+      log.warn "The `search_dirs` key is not available for the Windows `where` command in `find_files`."
+    end
   end
+  return find_command
+end
+
+-- TODO: Maybe just change this to `find`.
+-- TODO: Support `find` and maybe let people do other stuff with it as well.
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:256]: Yeah no, why rename it? Scope of PR also screens no

File: lua/telescope/builtin/files.lua [hunk 4]
```diff
@@ -145,106 +145,126 @@ files.grep_string = function(opts)
...
+  elseif 1 == vim.fn.executable "find" and vim.fn.has "win32" == 0 then
+    return "find"
+  elseif 1 == vim.fn.executable "where" then
+    return "where"
+  end
+end
+
+local function find_command_options(opts)
+  local command = which_find_command(opts)
   local find_command = opts.find_command
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:168]: You need to make adjustments here. If `find_command` is not passed in its nil and shortly after you add doing `table.insert` thats bad

Comment (Conni2461) [reply lua/telescope/builtin/files.lua:168]: Or for me it doesnt even work. No config

File: lua/telescope/builtin/files.lua [hunk 5]
```diff
@@ -145,106 +145,126 @@ files.grep_string = function(opts)
...
--- TODO: Maybe just change this to `find`.
--- TODO: Support `find` and maybe let people do other stuff with it as well.
-files.find_files = function(opts)
+local function which_find_command(opts)
+  local command = opts.find_command
+  if command then
+    return command[1]
+  end
+  if 1 == vim.fn.executable "fd" then
+    return "fd"
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:154]: With only that we will go from `{ "fd", "--type", "f" }` to only `"fd"` which is something different.

File: lua/telescope/builtin/files.lua (hunk 1 above)
Comment (pedro757) [reply lua/telescope/builtin/files.lua:152]: The `which_find_command` function is just to know the options to apply depending on which of these `fd, fdfind, rg, find or where` are using, if someone use a custom `find_command` generally `(idk if it's always the case)` the first element on that list will be the command

Comment (pedro757) [reply lua/telescope/builtin/files.lua:152]: if that custom command is not one of the mentioned, then it will bypass all the options `(all the if statements in find_command_options)` and return just the `find_command` the user set

File: lua/telescope/builtin/files.lua (hunk 2 above)
Comment (pedro757) [reply lua/telescope/builtin/files.lua:174]: `fd` and `fdfind` apparently are the same, `rg` is diferent.

Comment (pedro757) [reply lua/telescope/builtin/files.lua:174]: But I could not say they will be the same in every option they have. I only know `fd`, I wont put my hands in the fire for the other commads, that's why I didn't want to change anything there.

File: lua/telescope/builtin/files.lua (hunk 4 above)
Comment (pedro757) [reply lua/telescope/builtin/files.lua:168]: You're right

File: lua/telescope/builtin/files.lua (hunk 5 above)
Comment (pedro757) [reply lua/telescope/builtin/files.lua:154]: I'm going to fix this

File: lua/telescope/builtin/files.lua (hunk 2 above)
Comment (Conni2461) [reply lua/telescope/builtin/files.lua:178]: `fd` and `fdfind` are 100% the same tool. the command is just called `fdfind` on ubuntu vs `fd` on all other systems (arch, nix, ...)

Comment (Conni2461) [reply lua/telescope/builtin/files.lua:178]: Yeah i see that rg is slightly different. We could still pull it in like this

```lua
if command == "fd" or command == "fd_find" or command == "rg" then
  if hidden then
    table.insert(find_command, "--hidden")
  end
  if no_ignore then
    table.insert(find_command, "--no-ignore")
  end
  if follow then
    table.insert(find_command, "-L")
  end
  if search_dirs then
    if command ~= "rg" then
      table.insert(find_command, ".")
    end
    for _, v in pairs(search_dirs) do
      table.insert(find_command, v)
    end
  end
else if ...
```
cant we?

File: lua/telescope/builtin/files.lua [hunk 6]
```diff
@@ -145,10 +145,25 @@ files.grep_string = function(opts)
...
+  elseif 1 == vim.fn.executable "rg" then
+    return { "rg", "--files" }
+  elseif 1 == vim.fn.executable "find" and vim.fn.has "win32" == 0 then
+    return { "find", ".", "-type", "f" }
+  elseif 1 == vim.fn.executable "where" then
+    return { "where", "/r", ".", "*" }
+  end
+end
+
+local function get_find_command_options(opts)
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:164]: can we not make a new function for this ?

File: lua/telescope/builtin/files.lua (hunk 2 above)
Comment (pedro757) [reply lua/telescope/builtin/files.lua:178]: Haha, I just saw that [here](https://github.com/sharkdp/fd#on-ubuntu), let me fix that.

File: lua/telescope/builtin/files.lua [hunk 7]
```diff
@@ -145,10 +145,25 @@ files.grep_string = function(opts)
   }):find()
 end
 
--- TODO: Maybe just change this to `find`.
--- TODO: Support `find` and maybe let people do other stuff with it as well.
-files.find_files = function(opts)
-  local find_command = opts.find_command
+local function get_find_command(opts)
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:148]: either move this local function inside `builtin.find_files` or do something like this

```lua
local find_command = (function()
  if opts.find_command then
    return opts.find_command
  elseif 1 == vim.fn.executable "fd" then
    return { "fd", "--type", "f" }
  elseif 1 == vim.fn.executable "fdfind" then
    return { "fdfind", "--type", "f" }
  elseif 1 == vim.fn.executable "rg" then
    return { "rg", "--files" }
  elseif 1 == vim.fn.executable "find" and vim.fn.has "win32" == 0 then
    return { "find", ".", "-type", "f" }
  elseif 1 == vim.fn.executable "where" then
    return { "where", "/r", ".", "*" }
  end
end)()
```

There is no need to have a local function that is only used once

File: lua/telescope/builtin/files.lua (hunk 1 above)
Comment (Conni2461) [reply lua/telescope/builtin/files.lua]: yep

**Comment by pedro757** [comment]
Should I writte docs? I don't know how to use the treesitter docgen showed in the [CONRTIBUTING](https://github.com/nvim-telescope/telescope.nvim/blob/master/CONTRIBUTING.md) guide

The [doc/telescope.txt](https://github.com/nvim-telescope/telescope.nvim/blob/948f5adff28928d21207035035c0827c9ad92cbc/doc/telescope.txt#L754) looks good to me

File: lua/telescope/builtin/files.lua [hunk 8]
```diff
@@ -148,7 +148,22 @@ end
...
+      return { "fdfind", "--type", "f" }
+    elseif 1 == vim.fn.executable "rg" then
+      return { "rg", "--files" }
+    elseif 1 == vim.fn.executable "find" and vim.fn.has "win32" == 0 then
+      return { "find", ".", "-type", "f" }
+    elseif 1 == vim.fn.executable "where" then
+      return { "where", "/r", ".", "*" }
+    end
+  end)()
+  local command = find_command[1]
```
Comment (Conni2461) [inline lua/telescope/builtin/files.lua:166]: One last thing i just noticed while doing the final review. If we never find a command `find_command` is nil which would cause a error here. 

In line 228 is the check. We need to do that check now earlier before we actually do anything with `find_command`

**Comment by Conni2461** [comment]
No i think you dont need to write docs

File: lua/telescope/builtin/files.lua (hunk 8 above)
Comment (pedro757) [reply lua/telescope/builtin/files.lua:175]: done

**Review by Conni2461 — APPROVED** [review]
LGTM dont think it has any regression. I tested a couple of configurations.

Thanks :)
