### PR TITLE
Redraw results win after process_complete

### LINKED ISSUE #2667: Results are not displayed when filtering
### Description

The results pane stopped showing filtered candidates when filtering results. I need to press `<C-p>` to "re-enable" results display.

### Neovim version

```markdown
NVIM v0.10.0-dev-958+gafd0c648a8
```

### Operating system and version

Arch Linux x86_64

### Telescope version / branch / rev

Latests master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)

Checking external dependencies
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions =====
```

### Steps to reproduce

As in the GIF:
1. Open nvim with the minimal lua file provided below.
2. Run `:Telescope find_files`
3. Start typing some characters to filter the results (in my case `tmu`)
4. Note that after 3. the results pane doesn't display any ouput but there are candidates in the pane. By pressing `C-p` (i.e  moving the cursor) the results re-appear.

telescope

### Expected behavior

4. Above

### Actual behavior

3. Above

### Minimal config

```Lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install and configure plugins
local plugins = {
    {
        'nvim-telescope/telescope.nvim',
        dependencies = {
            'nvim-lua/plenary.nvim',
            { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
        },
        config = function()
            require('telescope').setup({})
        end,
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})
```

### PR DESCRIPTION
**Pull request by TwIStOy**
# Description

Fix #2667.
After process_complete, call `nvim_win_set_cursor` to redraw results win.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by max397574** [comment]
couldn't you just use `vim.cmd.redraw()`?

**Comment by TwIStOy** [comment]
i have tried, but it doesn't work.

File: lua/telescope/pickers.lua [hunk 1]
```diff
@@ -493,6 +493,14 @@ function Picker:find()
           log.warn("Finder failed with msg: ", msg)
         end
 
+        -- add an nvim_win_set_cursor to force the results win be redrawn
+        vim.schedule(function()
+          if not vim.api.nvim_win_is_valid(self.results_win) then
+            return
+          end
+          vim.api.nvim_win_set_cursor(self.results_win, vim.api.nvim_win_get_cursor(self.results_win))
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:501]: Would it be better to call `vim.cmd.redraw`?

```lua
vim.api.nvim_win_call(self.results_win, vim.cmd.redraw)
```

File: lua/telescope/pickers.lua [hunk 2]
```diff
@@ -512,6 +520,14 @@ function Picker:find()
 
         status_updater { completed = false }
         self._on_lines(...)
+
+        if self.sorting_strategy then
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:524]: This if condition is redundant.

File: lua/telescope/pickers.lua [hunk 3]
```diff
@@ -512,6 +520,14 @@ function Picker:find()
...
+          if self.sorting_strategy == "ascending" then
+            self:move_selection(1)
+          else
+            self:move_selection(-1)
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:528]: I can't tell what this block is actually for. Is it just another way to force a redraw?

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (TwIStOy) [reply lua/telescope/pickers.lua:501]: I have tried `redraw!`. But it doesn't work either.

File: lua/telescope/pickers.lua (hunk 2 above)
Comment (TwIStOy) [reply lua/telescope/pickers.lua:524]: Remove it!

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (lewis6991) [reply lua/telescope/pickers.lua:501]: Works for me.

```lua
        vim.schedule(function()
          vim.api.nvim_win_call(self.results_win, function()
            vim.cmd'redraw!'
          end)
        end)
```

File: lua/telescope/pickers.lua (hunk 3 above)
Comment (TwIStOy) [reply lua/telescope/pickers.lua]: Yeah. It's a way to force redraw the results win. The reason why not use `nvim_win_set_cursor` is in this case, the cursor's position should be recalculated.

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (lewis6991) [reply lua/telescope/pickers.lua:501]: In fact even this works for me:

```lua
        vim.schedule(function()
          vim.api.nvim_win_call(self.results_win, function()
            vim.cmd.redraw()
          end)
        end)
```

Comment (TwIStOy) [reply lua/telescope/pickers.lua:501]: Oh, it works. But i don't know, what's the difference between
```
          vim.api.nvim_win_call(self.results_win, function()
            vim.cmd "redraw!"
          end)
```

and

```
vim.cmd "redraw!"
```

Comment (max397574) [reply lua/telescope/pickers.lua:501]: just to make sure you used `nvim_win_call` and not just a simple `vim.cmd` right?

Comment (lewis6991) [reply lua/telescope/pickers.lua:501]: `nvim_win_call` changes the context to the picker window so that window is redrawn.

File: lua/telescope/pickers.lua (hunk 3 above)
Comment (lewis6991) [reply lua/telescope/pickers.lua]: I'm not sure what this fixes, but I didn't need it to fix the issues I am seeing.

Comment (max397574) [reply lua/telescope/pickers.lua]: just use another `nvim_win_call` with `redraw` and the other window?

Comment (lewis6991) [reply lua/telescope/pickers.lua]: Yeah. This works for me:

```lua
        vim.api.nvim_win_call(self.results_win, vim.cmd.redraw)
```

Comment (lewis6991) [reply lua/telescope/pickers.lua]: Scratch that, that doesn't always work, but this seems to:

```lua
        self:move_selection(self.sorting_strategy == "ascending" and 1 or -1)
```

Comment (TwIStOy) [reply lua/telescope/pickers.lua]: Try these steps to reproduce the issue:

- type a pattern to filter the results, and the number of results should be less than the height of results win
- delete char, and the number of results now is still less than the height of results win

In this case, the results win is empty.

I try `vim.api.nvim_win_call(self.results_win, function() vim.cmd "redraw!" end) ` to force redraw the results win. It works. But in this case, my statusline disappeared.

File: lua/telescope/pickers.lua (hunk 1 above)
Comment (TwIStOy) [reply lua/telescope/pickers.lua]: Ok. Update it using `redraw!`.

File: lua/telescope/pickers.lua [hunk 4]
```diff
@@ -493,6 +493,16 @@ function Picker:find()
           log.warn("Finder failed with msg: ", msg)
         end
 
+        -- add an nvim_win_set_cursor to force the results win be redrawn
+        vim.schedule(function()
+          if not vim.api.nvim_win_is_valid(self.results_win) then
+            return
+          end
+          vim.api.nvim_win_call(self.results_win, function()
+            vim.cmd "redraw!"
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:502]: Are you sure `!` is needed?

Otherwise this PR looks good.

Comment (TwIStOy) [reply lua/telescope/pickers.lua]: remove `!`:)

File: lua/telescope/pickers.lua [hunk 5]
```diff
@@ -512,6 +522,10 @@ function Picker:find()
 
         status_updater { completed = false }
         self._on_lines(...)
+
+        vim.api.nvim_win_call(self.results_win, function()
+          vim.cmd "redraw"
+        end)
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:528]: This doesn't actually work for me, but this does:

```lua
self:move_selection(self.sorting_strategy == "ascending" and 1 or -1)
```

Comment (TwIStOy) [reply lua/telescope/pickers.lua:528]: Emmm, that's strange. I will roll this back.

Comment (TwIStOy) [reply lua/telescope/pickers.lua:528]: maybe we can keep both?

File: lua/telescope/pickers.lua [hunk 6]
```diff
@@ -493,6 +493,16 @@ function Picker:find()
...
 
+        -- add an nvim_win_set_cursor to force the results win be redrawn
+        vim.schedule(function()
+          if not vim.api.nvim_win_is_valid(self.results_win) then
+            return
+          end
+          vim.api.nvim_win_call(self.results_win, function()
+            vim.cmd "redraw"
+          end)
+        end)
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:504]:
```suggestion
        await_schedule()
        if not vim.api.nvim_win_is_valid(self.results_win) then
          return
        end
        vim.api.nvim_win_call(self.results_win, vim.cmd.redraw)
```

File: lua/telescope/pickers.lua (hunk 5 above)
Comment (lewis6991) [reply lua/telescope/pickers.lua:528]: Putting `redraw` but in `vim.schedule` seems to work.

Comment (lewis6991) [inline lua/telescope/pickers.lua:528]:
```suggestion
        vim.schedule(function()
          if not vim.api.nvim_win_is_valid(self.results_win) then
            return
          end
          vim.api.nvim_win_call(self.results_win, vim.cmd.redraw)
        end)
```

Comment (lewis6991) [reply lua/telescope/pickers.lua:527]: Damm, now it's not working.

Sorry about this...

Comment (TwIStOy) [reply lua/telescope/pickers.lua:527]: Emm, then keep both?

Comment (lewis6991) [reply lua/telescope/pickers.lua:527]: Trying to reverse engineer this. So far this seems to work:

```lua
        self:reset_selection()
```

File: lua/telescope/pickers.lua [hunk 7]
```diff
@@ -525,6 +525,7 @@ function Picker:find()
           end
           vim.api.nvim_win_call(self.results_win, vim.cmd.redraw)
         end)
+        self:move_selection(self.sorting_strategy == "ascending" and 1 or -1)
```
Comment (lewis6991) [inline lua/telescope/pickers.lua:528]: Try changing this to `self:reset_selection` and moving it to under `self._reset_track()` above.

**Comment by lewis6991** [comment]
Ok... I think this may be the real fix:

```diff
diff --git a/lua/telescope/pickers.lua b/lua/telescope/pickers.lua
index 1ad989d..c2e8729 100644
--- a/lua/telescope/pickers.lua
+++ b/lua/telescope/pickers.lua
@@ -1337,6 +1337,8 @@ function Picker:get_result_completor(results_bufnr, find_id, prompt, status_upda
       local visible_result_rows = vim.api.nvim_win_get_height(self.results_win)
       vim.api.nvim_win_set_cursor(self.results_win, { self.max_results - visible_result_rows, 1 })
       vim.api.nvim_win_set_cursor(self.results_win, { self.max_results, 1 })
+    else
+      vim.api.nvim_win_set_cursor(self.results_win, { self:get_selection_row(), 0 })
     end
     self:_on_complete()
   end)
```

**Comment by TwIStOy** [comment]
> ```diff
>  vim.api.nvim_win_set_cursor(self.results_win, { self:get_selection_row(), 0 })
> ```

This works perfect!

**Review by lewis6991 — APPROVED** [review]

**Comment by jamestrew** [comment]
Lgtm as well. Thanks guys.
I had a suspicion that this isn't a redraw issue, like the cursor was just sitting at the top of the buffer with the results down at the bottom past the viewport of the window.

Maybe we can get some help with testing - make sure we haven't missed some edge case before merging.

**Comment by pedro757** [comment]
This breaks `sorting_strategy = "ascending"`

**Comment by lewis6991** [comment]
This should fix ascending:

```diff
diff --git a/lua/telescope/pickers.lua b/lua/telescope/pickers.lua
index 1ad989d..83384cc 100644
--- a/lua/telescope/pickers.lua
+++ b/lua/telescope/pickers.lua
@@ -1333,7 +1333,9 @@ function Picker:get_result_completor(results_bufnr, find_id, prompt, status_upda
     self:clear_extra_rows(results_bufnr)
     self.sorter:_finish(prompt)
 
-    if self.wrap_results and self.sorting_strategy == "descending" then
+    sorting_strategy = sorting_strategy or "descending"
+
+    if sorting_strategy == "descending" then
       local visible_result_rows = vim.api.nvim_win_get_height(self.results_win)
       vim.api.nvim_win_set_cursor(self.results_win, { self.max_results - visible_result_rows, 1 })
       vim.api.nvim_win_set_cursor(self.results_win, { self.max_results, 1 })
```

**Comment by jamestrew** [comment]
Looks like we have failing tests too. At least one of them related to `sorting_strategy = "ascending"`.

**Review by clason — APPROVED** [review]
That indeed seems to fix things (for default `vertical` layout).

**Review by jamestrew — APPROVED** [review]

**Comment by qgates** [comment]
It appears that the fix in 475c7d5 works when applied to the 0.1.x branch. Is there value in a PR for the fix on that branch or is it frozen?

**Comment by Conni2461** [comment]
patch was ported back to 0.1.x
