### PR TITLE
fix: correctly parse filenames with special chars in git_status

### LINKED ISSUE #2292: Telescope Git Status not escape file name properly
### Description

Currently, if a file contains a space in it, it will break the file. Also, if a file contains some special character, will break the file as well.

For example, a file name `hello world.txt` -> will output `world.txt"

image

I've debugged the code a bit, the file output is messed up at this [line](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/make_entry.lua#L1345)

Printing the value, it seems like when a file contains space(might be other cases as well), the git file is return with "" surrounding it which breaks the regex matching. 

### Neovim version

```markdown
:!nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 13.1

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
:!nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce

1. Create a new file name `hello world.txt`
2. Run `:Telescope git_status`

### Expected behavior

It should outputs `hello world.txt` file

### Actual behavior

Outputs world.txt\"

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by smjonas**
# Description

Fixes #2292. This uses `git status -z` instead of `git status --short` (see https://git-scm.com/docs/git-status/2.16.6#_porcelain_format_version_1) of which the output is easier to parse (e.g. filenames are not quoted). 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
In a Git repo with some files (`ls` shows `'$hey.txt'  '\esc2.txt'  '\esc.txt'   nenen.txt  'normal_"\renamed.txt'  '"qt.txt'  'two words.lua'`), then running `:Telescope git_status`.
The info from Git seems to be parsed correctly now and the file is opened as expected when pressing enter.

telescope_pr

The only things that's not working correctly yet is the previewer but that's a different issue (requiring updates to `from_entry.lua`).

**Configuration**:
* Neovim version (nvim --version): NVIM v0.9.0-dev-1729+g2d8bbe468     
* Operating system and version: Linux Mint 20.2 

# Checklist:

- [X] My code follows the style guidelines of this project (stylua)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: lua/telescope/builtin/__git.lua [hunk 1]
```diff
@@ -332,7 +332,7 @@ git.status = function(opts)
     end
 
     return finders.new_table {
-      results = output,
+      results = vim.split(output[1], " ", { trimempty = true }),
```
Comment (smjonas) [inline lua/telescope/builtin/__git.lua:335]: For some reason, GitHub cuts off the preview after the NUL character. It's shown correctly here: https://github.com/nvim-telescope/telescope.nvim/blob/889ef096d11fd4b9476c0409be544a9d8460a2b8/lua/telescope/builtin/__git.lua#L335

Comment (smjonas) [inline lua/telescope/builtin/__git.lua:335]: There is a NUL character inside of the quotes that's not shown on GitHub

**Comment by Conni2461** [comment]
Thanks :)

CI failure is unrelated

**Comment by LinoWhy** [comment]
It's changed by #2789, so a filename with 'space' is still quoted. 
Any idea to fix it?
