### PR TITLE
fix: make keepinsert work with nvim-0.7

### LINKED ISSUE #1599: actions._close(bufnr, true) exits insert mode
### Description

I have noticed that plugins that change from one picker to another or even builtin pickers (`:Telescope builtin`) quit insert mode when not intended.

### Neovim version

```markdown
NVIM v0.7.0-dev+22d7dd2ae
Build type: Release
```

### Operating system and version

macOs 12.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. nvim -nu minimal.lua
2. :Telescope builtin
3. Select a builtin

### Expected behavior

I was expecting to stay in insert mode

### Actual behavior

Vim mode is changed to Normal

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by kylo252**
Ensure that `keepinsert` works correctly in `actions._close()` in nvim-0.7 after https://github.com/neovim/neovim/commit/28134f4e78819c2bbf0344326b9d44f21eb0d736

Fixes #1599

### CODE REVIEW

**Comment by fdschmidt93** [comment]
Yeah, I was trying something similar, but that doesn't seem to work for instance with `:Telescope pickers` when you select a picker that already had text. Maybe that requires a separate fix?

**Comment by kylo252** [comment]
> Yeah, I was trying something similar, but that doesn't seem to work for instance with `:Telescope pickers` when you select a picker that already had text. Maybe that requires a separate fix?

I have no idea how to use this 😅

**Comment by fdschmidt93** [comment]
Sorry, I should have expressed myself more clearly. This solution has the following issue:

1. Do e.g. `builtin.find_files` and search for something; keep the search string in the prompt
2. Close the picker
3. Open the `:Telescope pickers`
4. Re-open the previously closed picker with the corresponding query
5. The picker is opened correctly in insert mode, but the query is not adequately kept in the prompt

> but the query is not adequately kept in the prompt

This part I was referring to may require a separate fix, because I don't have a good sense of how to fix the remaining in insert mode issue other than how you're doing it as part of this PR.

**Comment by kylo252** [comment]
Thanks for the explanation! It led me to what I believe is the actual correct fix for this.

- works for me on both v0.6.0 and v0.7.0-dev+737-g818ae74ea
 - also works for `:Telescope pickers`

**Comment by fdschmidt93** [comment]
This seems to work generally well for me for the scenarios I've tested but I'm wary that in particular scheduling `set_prompt` may have unintended interactions in for the time being untested scenarios :sweat_smile: Though that may just as well not be the case.

Since it's something rather lower level, I'd prefer a separate set of eyes on this as well prior to merging.

**Comment by Conni2461** [comment]
The prompt_buffer fixes are merge so it should now be possible to just set the prompt without using feedkeys

```lua
  local prompt_text = self.prompt_prefix .. (str or "")
  vim.api.nvim_buf_set_lines(self.prompt_bufnr, 0, 1, false, { prompt_text })
  vim.api.nvim_win_set_cursor(self.prompt_win, { 1, #prompt_text })
  self:_reset_prefix_color()
```

File: lua/telescope/pickers.lua [hunk 1]
```diff
@@ -414,13 +414,15 @@ function Picker:find()
     pcall(a.nvim_buf_set_option, prompt_bufnr, "filetype", "TelescopePrompt")
     pcall(a.nvim_buf_set_option, results_bufnr, "filetype", "TelescopeResults")
 
-    -- TODO(async): I wonder if this should actually happen _before_ we nvim_buf_attach.
-    -- This way the buffer would always start with what we think it should when we start the loop.
```
Comment (Conni2461) [inline lua/telescope/pickers.lua:418]: why are you removing todos ?

Comment (kylo252) [reply lua/telescope/pickers.lua:418]: I figured that this PR adds the async part, just in a different way, while the suggested way wouldn't work anymore.

Comment (Conni2461) [reply lua/telescope/pickers.lua:418]: not really but its no longer possible due to prompt buffer changes anyway. So its leave it removed

**Comment by Conni2461** [comment]
Are you also fixing `set_prompt`? So it works for 0.6 and current nightly?

**Comment by kylo252** [comment]
> Are you also fixing `set_prompt`? So it works for 0.6 and current nightly?

Done! 

I think I've tried most scenarios and all of them seem to work correctly for me using this configuration on both 0.6 and nightly. Please give it a try and let me know if I've missed something.

**Comment by fdschmidt93** [comment]
Slight issue seems to apply here:

1. Do e.g. builtin.find_files and search for something; keep the search string in the prompt
2. Close the picker
3. Open the :Telescope pickers
4. Re-open the previously closed picker with the corresponding query
5. Correctly in insert mode but cursor is incorrectly on the second-to-last character

**Comment by kylo252** [comment]
> Slight issue seems to apply here

I don't have that problem on either nightly or 0.6, at least not with find_files.

**Comment by fdschmidt93** [comment]
Retried with `minimal_init.lua` with video attached. Not sure why I do and you don't have this problem :/

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        -- 'nvim-telescope/telescope.nvim',
        'kylo252/telescope.nvim',
        branch = "nvim-nightly-compat",
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

https://user-images.githubusercontent.com/39233597/147658023-6a3d33f3-ed70-43f6-9301-2d64066daa95.mp4

**Comment by kylo252** [comment]
@fdschmidt93, I can reproduce on this machine at least, although I'm not really sure how to solve this. I tried a few different things and none of them worked. 

Do we still need to call this directly?
https://github.com/nvim-telescope/telescope.nvim/blob/1d1da664eb6505c318d405eea3d633c451edc2d8/lua/telescope/pickers.lua#L389

Why is this one adding a `+1` while the function that @Conni2461 suggested doesn't?
https://github.com/nvim-telescope/telescope.nvim/blob/1d1da664eb6505c318d405eea3d633c451edc2d8/lua/telescope/pickers.lua#L1404-L1407

Aren't these two functions the same?
https://github.com/nvim-telescope/telescope.nvim/blob/1d1da664eb6505c318d405eea3d633c451edc2d8/lua/telescope/pickers.lua#L1453-L1456

**Comment by fdschmidt93** [comment]
Apologies, I'm quite tied up at the moment and hopefully will get to look more into this at some point this week but the little time I have is probably spent on `telescope-file-browser.nvim` docs and stuff so it can be finally removed from `telescope-core` prior to me (possibly) going on a hiatus till February. That said, I've also tried a few things when I reported it to no avail.

To the changes/inconsistencies you've mentioned. At very first initial glance, just looks like some debt acquired over time? I presume that can be cleaned up?

**Comment by przepompownia** [comment]
Additionally, the original selection is then lost when I try to reuse it by `gv`.

File: lua/telescope/pickers.lua [hunk 2]
```diff
@@ -419,11 +419,11 @@ function Picker:find()
...
     if self.initial_mode == "insert" or self.initial_mode == "normal" then
       -- required for set_prompt to work adequately
-      vim.cmd [[startinsert!]]
+      vim.schedule(function()
```
Comment (przepompownia) [inline lua/telescope/pickers.lua:424]:
```diff
diff --git a/lua/telescope/pickers.lua b/lua/telescope/pickers.lua
index d91ae5c..3889ebf 100644
--- a/lua/telescope/pickers.lua
+++ b/lua/telescope/pickers.lua
@@ -422,6 +422,10 @@ function Picker:find()
     if self.initial_mode == "insert" or self.initial_mode == "normal" then
       -- required for set_prompt to work adequately
       vim.schedule(function()
+        if vim.fn.mode() == 'v' then
+          local key = vim.api.nvim_replace_termcodes("<ESC>", true, false, true)
+          vim.api.nvim_feedkeys(key, "i", true)
+        end
         vim.cmd [[startinsert!]]
       end)
       if self.default_text then
```
Maybe it's not the best solution but it lets me avoid manual exiting from _insert (visual)_ mode.

Comment (Conni2461) [reply lua/telescope/pickers.lua:424]: I think we should deal with opening telescope from visual mode some other time. Ill open a new issue

Comment (Conni2461) [reply lua/telescope/pickers.lua:424]: Better idea, we make your issue about problems opening telescope from visual mode

**Comment by Conni2461** [comment]
@fdschmidt93 I am currently trying to fix the bug you reported here: https://github.com/nvim-telescope/telescope.nvim/pull/1600#issuecomment-1002048543

After that this one is ready

**Comment by Conni2461** [comment]
Seems to be fixed for me. Do you have a couple of minutes to validate? Thanks :)

**Comment by fdschmidt93** [comment]
Works flawlessly, I've spend 20 minutes to test all the weird combinations I could think of around `builtin.builtin`, launching a picker from within another picker and `Telescope pickers` them afterwards. The previous combination with outer product (hopefully complete :laughing:) of with `default_text` and varying `initial_mode`. (eg launch picker no

Truth be told, sometimes the cursor minimally glitches into insert mode, though from having worked on this a also quite bit back then and seeing your solution, I'm fairly confident that this unfortunately cannot be avoided. I'd say let's merge, great job :)

**Comment by Conni2461** [comment]
Ill have to merge after #1851. My merge window today is 3 - 4pm german time.

> E: Ah, can we unify actions._close and actions.close now that keepinsert is no longer a parameter? Am I missing something?

 I added a comment that its deprecated but we can't just remove it because a lot of extensions still call it. So right now its just an "alias".

File: lua/telescope/builtin/internal.lua [hunk 3]
```diff
@@ -178,9 +178,10 @@ internal.pickers = function(opts)
       actions.select_default:replace(function(prompt_bufnr)
         local current_picker = action_state.get_current_picker(prompt_bufnr)
         local selection_index = current_picker:get_index(current_picker:get_selection_row())
-        actions._close(prompt_bufnr, cached_pickers[selection_index].initial_mode == "insert")
+        actions.close(prompt_bufnr)
         opts.cache_picker = opts._cache_picker
         opts["cache_index"] = selection_index
+        opts["initial_mode"] = cached_pickers[selection_index].initial_mode
```
Comment (Conni2461) [inline lua/telescope/builtin/internal.lua:184]: Does this capture the correct intend?

File: lua/telescope/pickers.lua (hunk 2 above)
Comment (Conni2461) [reply lua/telescope/pickers.lua:440]: @przepompownia Its fixed because i already had to fix opening telescope from insert mode, because previously that was working. So yeah why not

**Comment by Conni2461** [comment]
@clason I just validated this: https://github.com/nvim-telescope/telescope.nvim/issues/1072#issue-958930038 

Is it the correct behavior that if i do `|foobar` i end up with `fX|oobar` ? Happens on master as well as this branch. Everything else seems to work for me

**Comment by clason** [comment]
No, that is not intended (and happens for me, too). It's virtually impossible to make the insert mode symbol insertion work correctly in all situations -- it's a veritable whack-a-mole game...

**Comment by Conni2461** [comment]
okay thanks :) i just had to make sure i dont make it worse, after these "mode" changes

**Comment by clason** [comment]
If that's the only situation that doesn't work properly (as in, inserting behaves the same as typing the character in insert mode), then you're fine ;)

(Otherwise we have a problem :])

**Comment by przepompownia** [comment]
Quick manual tests after fetching new changes gives expected results both on the testing and my working environment :tada:

File: lua/telescope/actions/init.lua [hunk 4]
```diff
@@ -343,28 +343,25 @@ end
...
-    vim.cmd [[stopinsert]]
-  end
 
   vim.api.nvim_win_close(prompt_win, true)
   pcall(vim.cmd, string.format([[silent bdelete! %s]], prompt_bufnr))
   pcall(a.nvim_set_current_win, original_win_id)
 end
 
+--- Close the Telescope window, usually used within an action<br>
+--- Deprecated and no longer needed, does the same as |telescope.actions.close|. Might be removed in the future
```
Comment (kylo252) [inline lua/telescope/actions/init.lua:359]: maybe use the `---@deprecated` tag instead? 
ref: https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#deprecated

File: lua/telescope/actions/init.lua [hunk 5]
```diff
@@ -343,28 +343,25 @@ end
...
-  actions._close(prompt_bufnr, false)
-end
-
---- Close the Telescope window and specify if you want to keep insert mode or not
----@param prompt_bufnr number: The prompt bufnr
----@param keepinsert boolean: Remain in INSERT mode if true
-actions._close = function(prompt_bufnr, keepinsert)
   action_state.get_current_history():reset()
   local picker = action_state.get_current_picker(prompt_bufnr)
   local prompt_win = state.get_status(prompt_bufnr).prompt_win
```
Comment (kylo252) [inline lua/telescope/actions/init.lua:348]: shouldn't we validate this value? or bail out early otherwise?

File: lua/telescope/builtin/internal.lua (hunk 3 above)
Comment (fdschmidt93) [reply lua/telescope/builtin/internal.lua:184]: Yes, works as it should around cached pickers with `:Telescope pickers`.

File: lua/telescope/pickers.lua [hunk 6]
```diff
@@ -432,21 +432,22 @@ function Picker:find()
...
+    if self.initial_mode == "insert" then
+      vim.schedule(function()
+        -- startinsert! did not reliable do `A` no idea why, i even looked at the source code
+        -- Example: live_grep -> type something -> quit -> Telescope pickers -> resume -> cursor of by one
+        local mode = vim.fn.mode()
+        if mode == "n" then
+          vim.api.nvim_feedkeys("A", "n", true)
+        elseif mode == "v" then
+          vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<ESC>A", true, false, true), "n", true)
+        end
```
Comment (kylo252) [inline lua/telescope/pickers.lua:448]:
```suggestion
        if mode ~= "i" then
          vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<ESC>A", true, false, true), "n", true)
        end
```

this seems to work for me

File: lua/telescope/pickers.lua (hunk 2 above)
Comment (przepompownia) [reply lua/telescope/pickers.lua:440]: Commented outside this thread: https://github.com/nvim-telescope/telescope.nvim/pull/1600#issuecomment-1106402968

File: lua/telescope/actions/init.lua (hunk 5 above)
Comment (Conni2461) [reply lua/telescope/actions/init.lua:348]: ?

Comment (kylo252) [reply lua/telescope/actions/init.lua:348]:
```lua
if not vim.api.nvim_win_is_valid(prompt_win) then
  -- nothing to do | raise error
  return
end
```

Comment (Conni2461) [reply lua/telescope/actions/init.lua:348]: worked for the past year. If you call this function outside of a telescope action, its undefined behavior
