### PR TITLE
fix: exiting picker from insert mode

### LINKED ISSUE #1185: calling Telescope built-in picker moves cursor to the left by one
### Description

After mapping `<esc>` to exit Telescope picker and calling e.g. `:Telescope find_files` or any other built-in picker, the cursor will be shifted to the left by one.

### Neovim version

NVIM v0.6.0-dev+205-g9695691ee

### Operating system and version

Linux arch 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

### Steps to reproduce

example having a line "foobar":
```
foobar
cursor at 'r'
:Telescope find_files
exit picker either by pressing <esc> or <c-[>
now cursor at 'a'
```

### Expected behavior

Cursor does not move.

### Actual behavior

Moves one to the left.

### Minimal config

```Lua
call plug#begin('$XDG_DATA_HOME/nvim/site/plugged')
	Plug 'nvim-lua/popup.nvim'
	Plug 'nvim-lua/plenary.nvim'
	Plug 'nvim-telescope/telescope.nvim'
call plug#end()

lua << EOF
require('telescope').setup{
	defaults = { mappings = { i = { ["<esc>"] = require('telescope.actions').close, }, }, },
}
EOF
```

### PR DESCRIPTION
**Pull request by fdschmidt93**
Closes #1185 

This is quite similar to #1165. If I understand it correctly `vim.cmd [[stopinsert]]` is just too slow. So I guess what happens then is you actually land in the original window in insert mode and only leave it there, which, being on the original cursor position, means you exit insert mode to land in one column to the left. (Conversely, exitting in normal mode works just fine).

The other solution I supposed would be to await `vim.cmd` though this should surely feel faster (& not sure how I'd to that in new plenary async).

### CODE REVIEW

File: lua/telescope/actions/init.lua [hunk 1]
```diff
@@ -287,6 +290,11 @@ actions._close = function(prompt_bufnr, keepinsert)
   actions.close_pum(prompt_bufnr)
   if not keepinsert then
     vim.cmd [[stopinsert]]
+    await_schedule(function()
+      if a.nvim_win_is_valid(original_win_id) then
+        a.nvim_win_set_cursor(original_win_id, original_cursor)
+      end
+    end)
```
Comment (tjdevries) [inline lua/telescope/actions/init.lua:297]: Can this not just get placed beneath the pcall on line 303 for set_current_win? I don't thin we need to do it this way.

Just `pcall(a.nvim_win_set_cursor, original_win_id, original_cursor)` or similar

Comment (fdschmidt93) [reply lua/telescope/actions/init.lua:297]: No, tried it an desn't work. `stopinsert` for some reason only takes effect afterwards. So when you set the cursor position to where it's supposed to be while being in insert mode, you'll end up one to the left when exitting.

I tried a bunch of things to fix this 😅 it's not that I like this one all too much, it was just the only one that worked.

**Comment by mortezadadgar** [comment]
Any update on this issue

**Comment by muniter** [comment]
> Closes #1185 
> 
> This is quite similar to #1165. If I understand it correctly `vim.cmd [[stopinsert]]` is just too slow. So I guess what happens then is you actually land in the original window in insert mode and only leave it there

This would explain #856

**Comment by darzok0914** [comment]
any update on this PR?

**Comment by Conni2461** [comment]
rebased it.

If you are using vim-startify, my cursor e.g. is at `15:5`, i open a file. Its still there. It also happens if i am at file A line 100. Open telescope goto file B. I end up at line 100. 

So we basically only want this on `<C-c>` not on `<CR>`

**Comment by fdschmidt93** [comment]
@Conni2461 ok to move history reset to `on_close_prompt`? Seems like the most appropriate place, since we have to avoid meddling with the original window if we eg to select_{vertical, horizontal, ...} as otherwise if we'd set the cursor, going back to the original window would place the cursor one too far to the right (if that makes sense).

For some reason, I cannot leave insert mode fast enough in `actions.close` so well, we just adjust the cursor.

**Comment by Conni2461** [comment]
> Ok to move history reset to on_close_prompt?

Yes. Works for me. Fix also works for me. Thanks. Merging to master because its a ffix

> For some reason, I cannot leave insert mode fast enough in actions.close so well, we just adjust the cursor.

Would be great if we could leave insert before doing `:edit` (...) also because of this https://github.com/nvim-telescope/telescope.nvim/issues/559#issuecomment-1002803413

`:help stopinsert`
> Stop Insert mode or |Terminal-mode| as soon as possible.

**Review by Conni2461 — APPROVED** [review]

**Comment by ajitid** [comment]
Do we have a different ticket to stop cursor moving to the left when Enter key is pressed?

What I'm doing here:
1. Open `:Telescope buffers`
2. Hit Enter key
3. Watch cursor moving to the left
4. Repeat 

https://user-images.githubusercontent.com/26769888/169488940-fe10be4e-8358-471d-876f-ed1ebd300c3c.mp4

(Can confirm the PR works just fine for <c-c> and <esc> keys.)

**Comment by clason** [comment]
I'm afraid this broke `actions.insert_symbol_i` again...

(I.e., triggering it on `foo|bar` puts the symbol after the `b` instead of the cursor position.)

**Comment by fdschmidt93** [comment]
I'm very sure I'm misunderstanding something here, but looks as intended for me..?

https://user-images.githubusercontent.com/39233597/171050067-e45851c3-13ca-4337-8ac3-c7a1a9a772db.mp4

**Comment by clason** [comment]
That doesn't look like the symbol inserter to me?

(on mobile, will share config when I get home)

**Comment by clason** [comment]
Make sure to have trailing characters! If you insert at the end of a line, you obviously won't see the issue.
